<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Errors | QLQ学习平台</title>
    <meta name="description" content="QLQ学习平台">
    <link rel="manifest" href="/public/blog/manifest.json">
    
    <link rel="preload" href="/public/blog/assets/css/0.styles.3ad33863.css" as="style"><link rel="preload" href="/public/blog/assets/js/app.793d18d6.js" as="script"><link rel="preload" href="/public/blog/assets/js/2.d1dd4e4d.js" as="script"><link rel="preload" href="/public/blog/assets/js/25.151f485c.js" as="script"><link rel="preload" href="/public/blog/assets/js/3.1f730cd9.js" as="script"><link rel="prefetch" href="/public/blog/assets/js/10.7d4b1d4b.js"><link rel="prefetch" href="/public/blog/assets/js/11.c135c766.js"><link rel="prefetch" href="/public/blog/assets/js/12.17db24c5.js"><link rel="prefetch" href="/public/blog/assets/js/13.6e07cbcf.js"><link rel="prefetch" href="/public/blog/assets/js/14.ea2a0d07.js"><link rel="prefetch" href="/public/blog/assets/js/15.a6a7563b.js"><link rel="prefetch" href="/public/blog/assets/js/16.956a9122.js"><link rel="prefetch" href="/public/blog/assets/js/17.06ff4bf4.js"><link rel="prefetch" href="/public/blog/assets/js/18.a604e43f.js"><link rel="prefetch" href="/public/blog/assets/js/19.43fdc1b1.js"><link rel="prefetch" href="/public/blog/assets/js/20.faad6d2d.js"><link rel="prefetch" href="/public/blog/assets/js/21.554b2f54.js"><link rel="prefetch" href="/public/blog/assets/js/22.961d3c7f.js"><link rel="prefetch" href="/public/blog/assets/js/23.98032a48.js"><link rel="prefetch" href="/public/blog/assets/js/24.735ada0c.js"><link rel="prefetch" href="/public/blog/assets/js/26.f3d12769.js"><link rel="prefetch" href="/public/blog/assets/js/27.d91bf872.js"><link rel="prefetch" href="/public/blog/assets/js/28.2a36a68f.js"><link rel="prefetch" href="/public/blog/assets/js/29.78b1b45d.js"><link rel="prefetch" href="/public/blog/assets/js/30.7481d4c5.js"><link rel="prefetch" href="/public/blog/assets/js/31.16e7c775.js"><link rel="prefetch" href="/public/blog/assets/js/32.75fed837.js"><link rel="prefetch" href="/public/blog/assets/js/33.cf2e0b8f.js"><link rel="prefetch" href="/public/blog/assets/js/34.4221897d.js"><link rel="prefetch" href="/public/blog/assets/js/35.97e4fc88.js"><link rel="prefetch" href="/public/blog/assets/js/36.137598cd.js"><link rel="prefetch" href="/public/blog/assets/js/37.9b12e9de.js"><link rel="prefetch" href="/public/blog/assets/js/38.8d385bd4.js"><link rel="prefetch" href="/public/blog/assets/js/39.c2d2376a.js"><link rel="prefetch" href="/public/blog/assets/js/4.a6ed393e.js"><link rel="prefetch" href="/public/blog/assets/js/40.a2197e85.js"><link rel="prefetch" href="/public/blog/assets/js/41.6e6eb90b.js"><link rel="prefetch" href="/public/blog/assets/js/42.ba8fc1fa.js"><link rel="prefetch" href="/public/blog/assets/js/43.561011ab.js"><link rel="prefetch" href="/public/blog/assets/js/44.0e624559.js"><link rel="prefetch" href="/public/blog/assets/js/45.31eb2ed7.js"><link rel="prefetch" href="/public/blog/assets/js/46.33d8378f.js"><link rel="prefetch" href="/public/blog/assets/js/47.18b18711.js"><link rel="prefetch" href="/public/blog/assets/js/48.84db573a.js"><link rel="prefetch" href="/public/blog/assets/js/49.e007afae.js"><link rel="prefetch" href="/public/blog/assets/js/5.868620b4.js"><link rel="prefetch" href="/public/blog/assets/js/50.05e06075.js"><link rel="prefetch" href="/public/blog/assets/js/51.28689d1c.js"><link rel="prefetch" href="/public/blog/assets/js/52.84b0ef5c.js"><link rel="prefetch" href="/public/blog/assets/js/53.693b991f.js"><link rel="prefetch" href="/public/blog/assets/js/54.3ebbd2e5.js"><link rel="prefetch" href="/public/blog/assets/js/55.c466c411.js"><link rel="prefetch" href="/public/blog/assets/js/56.02fb13e9.js"><link rel="prefetch" href="/public/blog/assets/js/57.a0811a6e.js"><link rel="prefetch" href="/public/blog/assets/js/58.ef3c4301.js"><link rel="prefetch" href="/public/blog/assets/js/59.5ecba546.js"><link rel="prefetch" href="/public/blog/assets/js/6.8e0ec0a1.js"><link rel="prefetch" href="/public/blog/assets/js/60.41e35580.js"><link rel="prefetch" href="/public/blog/assets/js/61.51154b06.js"><link rel="prefetch" href="/public/blog/assets/js/62.e557785e.js"><link rel="prefetch" href="/public/blog/assets/js/63.6ee35392.js"><link rel="prefetch" href="/public/blog/assets/js/64.5bb83569.js"><link rel="prefetch" href="/public/blog/assets/js/65.b26f077a.js"><link rel="prefetch" href="/public/blog/assets/js/7.287519a5.js"><link rel="prefetch" href="/public/blog/assets/js/8.ad4df861.js"><link rel="prefetch" href="/public/blog/assets/js/9.ef0461e8.js">
    <link rel="stylesheet" href="/public/blog/assets/css/0.styles.3ad33863.css">
  </head>
  <body>
    <div id="app" data-server-rendered="true"><div class="theme-container"><header class="navbar"><div class="sidebar-button"><svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" viewBox="0 0 448 512" class="icon"><path fill="currentColor" d="M436 124H12c-6.627 0-12-5.373-12-12V80c0-6.627 5.373-12 12-12h424c6.627 0 12 5.373 12 12v32c0 6.627-5.373 12-12 12zm0 160H12c-6.627 0-12-5.373-12-12v-32c0-6.627 5.373-12 12-12h424c6.627 0 12 5.373 12 12v32c0 6.627-5.373 12-12 12zm0 160H12c-6.627 0-12-5.373-12-12v-32c0-6.627 5.373-12 12-12h424c6.627 0 12 5.373 12 12v32c0 6.627-5.373 12-12 12z"></path></svg></div> <a href="/public/blog/" class="home-link router-link-active"><!----> <span class="site-name">QLQ学习平台</span></a> <div class="links"><div class="search-box"><input aria-label="Search" autocomplete="off" spellcheck="false" value=""> <!----></div> <nav class="nav-links can-hide"><div class="nav-item"><a href="/public/blog/js/regexp.html" class="nav-link">javaScript</a></div><div class="nav-item"><a href="/public/blog/css/bfc.html" class="nav-link">css</a></div><div class="nav-item"><a href="/public/blog/webpack/base-config.html" class="nav-link">webpack</a></div><div class="nav-item"><a href="/public/blog/node/nodemon.html" class="nav-link">node</a></div><div class="nav-item"><a href="/public/blog/fragment/angular.html" class="nav-link">js框架</a></div><div class="nav-item"><a href="/public/blog/pwa/PWA.html" class="nav-link">pwa</a></div> <!----></nav></div></header> <div class="sidebar-mask"></div> <aside class="sidebar"><nav class="nav-links"><div class="nav-item"><a href="/public/blog/js/regexp.html" class="nav-link">javaScript</a></div><div class="nav-item"><a href="/public/blog/css/bfc.html" class="nav-link">css</a></div><div class="nav-item"><a href="/public/blog/webpack/base-config.html" class="nav-link">webpack</a></div><div class="nav-item"><a href="/public/blog/node/nodemon.html" class="nav-link">node</a></div><div class="nav-item"><a href="/public/blog/fragment/angular.html" class="nav-link">js框架</a></div><div class="nav-item"><a href="/public/blog/pwa/PWA.html" class="nav-link">pwa</a></div> <!----></nav>  <ul class="sidebar-links"><li><section class="sidebar-group depth-0"><p class="sidebar-heading open"><span>node</span> <!----></p> <ul class="sidebar-links sidebar-group-items"><li><a href="/public/blog/node/buffer.html" class="sidebar-link">Buffer</a></li><li><a href="/public/blog/node/stream.html" class="sidebar-link">Stream</a></li><li><a href="/public/blog/node/nodemon.html" class="sidebar-link">nodemon：高效的nodejs开发环境</a></li></ul></section></li></ul> </aside> <main class="page"> <div class="theme-default-content content__default"><h1 id="errors"><a href="#errors" class="header-anchor">#</a> Errors</h1> <p>Applications running in Node.js will generally experience four categories of
errors:</p> <ul><li>Standard JavaScript errors such as {EvalError}, {SyntaxError}, {RangeError},
{ReferenceError}, {TypeError}, and {URIError}.</li> <li>System errors triggered by underlying operating system constraints such
as attempting to open a file that does not exist or attempting to send data
over a closed socket.</li> <li>User-specified errors triggered by application code.</li> <li><code>AssertionError</code>s are a special class of error that can be triggered when
Node.js detects an exceptional logic violation that should never occur. These
are raised typically by the <code>assert</code> module.</li></ul> <p>All JavaScript and System errors raised by Node.js inherit from, or are
instances of, the standard JavaScript {Error} class and are guaranteed
to provide <em>at least</em> the properties available on that class.</p> <h2 id="error-propagation-and-interception"><a href="#error-propagation-and-interception" class="header-anchor">#</a> Error Propagation and Interception</h2> <p>Node.js supports several mechanisms for propagating and handling errors that
occur while an application is running. How these errors are reported and
handled depends entirely on the type of <code>Error</code> and the style of the API that is
called.</p> <p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate
and throw an error using the standard JavaScript <code>throw</code> mechanism. These
are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" target="_blank" rel="noopener noreferrer"><code>try…catch</code> construct<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a> provided by the
JavaScript language.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token comment">// Throws with a ReferenceError because z is not defined.</span>
<span class="token keyword">try</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> m <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> n <span class="token operator">=</span> m <span class="token operator">+</span> z<span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// Handle the error here.</span>
<span class="token punctuation">}</span>
</code></pre></div><p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that
<em>must</em> be handled using <code>try…catch</code> or the Node.js process will exit
immediately.</p> <p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not
accept a <code>callback</code> function, such as <a href="/public/blog/node/fs.html#fs_fs_readfilesync_path_options"><code>fs.readFileSync</code></a>), will use <code>throw</code>
to report errors.</p> <p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p> <ul><li>Most asynchronous methods that accept a <code>callback</code> function will accept an
<code>Error</code> object passed as the first argument to that function. If that first
argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred
that should be handled.</li></ul> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> fs <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'fs'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
fs<span class="token punctuation">.</span><span class="token function">readFile</span><span class="token punctuation">(</span><span class="token string">'a file that does not exist'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">err<span class="token punctuation">,</span> data</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'There was an error reading the file!'</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// Otherwise handle the data</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><ul><li><p>When an asynchronous method is called on an object that is an
<a href="/public/blog/node/events.html#events_class_eventemitter"><code>EventEmitter</code></a>, errors can be routed to that object's <code>'error'</code> event.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> net <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'net'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> connection <span class="token operator">=</span> net<span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span><span class="token string">'localhost'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Adding an 'error' event handler to a stream:</span>
connection<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'error'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">err</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  <span class="token comment">// If the connection is reset by the server, or if it can't</span>
  <span class="token comment">// connect at all, or on any sort of error encountered by</span>
  <span class="token comment">// the connection, the error will be sent here.</span>
  console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

connection<span class="token punctuation">.</span><span class="token function">pipe</span><span class="token punctuation">(</span>process<span class="token punctuation">.</span>stdout<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div></li> <li><p>A handful of typically asynchronous methods in the Node.js API may still
use the <code>throw</code> mechanism to raise exceptions that must be handled using
<code>try…catch</code>. There is no comprehensive list of such methods; please
refer to the documentation of each method to determine the appropriate
error handling mechanism required.</p></li></ul> <p>The use of the <code>'error'</code> event mechanism is most common for <a href="/public/blog/node/stream.html">stream-based</a>
and <a href="/public/blog/node/events.html#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of
asynchronous operations over time (as opposed to a single operation that may
pass or fail).</p> <p>For <em>all</em> <a href="/public/blog/node/events.html#events_class_eventemitter"><code>EventEmitter</code></a> objects, if an <code>'error'</code> event handler is not
provided, the error will be thrown, causing the Node.js process to report an
uncaught exception and crash unless either: The <a href="/public/blog/node/domain.html"><code>domain</code></a> module is
used appropriately or a handler has been registered for the
<a href="/public/blog/node/process.html#process_event_uncaughtexception"><code>'uncaughtException'</code></a> event.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> EventEmitter <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'events'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> ee <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token function">setImmediate</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
  <span class="token comment">// This will crash the process because no 'error' event</span>
  <span class="token comment">// handler has been added.</span>
  ee<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token string">'error'</span><span class="token punctuation">,</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'This will crash'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p>Errors generated in this way <em>cannot</em> be intercepted using <code>try…catch</code> as
they are thrown <em>after</em> the calling code has already exited.</p> <p>Developers must refer to the documentation for each method to determine
exactly how errors raised by those methods are propagated.</p> <h3 id="error-first-callbacks"><a href="#error-first-callbacks" class="header-anchor">#</a> Error-first callbacks</h3> <p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic
pattern referred to as an <em>error-first callback</em>. With this pattern, a callback
function is passed to the method as an argument. When the operation either
completes or an error is raised, the callback function is called with the
<code>Error</code> object (if any) passed as the first argument. If no error was raised,
the first argument will be passed as <code>null</code>.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> fs <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'fs'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">function</span> <span class="token function">errorFirstCallback</span><span class="token punctuation">(</span><span class="token parameter">err<span class="token punctuation">,</span> data</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'There was an error'</span><span class="token punctuation">,</span> err<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

fs<span class="token punctuation">.</span><span class="token function">readFile</span><span class="token punctuation">(</span><span class="token string">'/some/file/that/does-not-exist'</span><span class="token punctuation">,</span> errorFirstCallback<span class="token punctuation">)</span><span class="token punctuation">;</span>
fs<span class="token punctuation">.</span><span class="token function">readFile</span><span class="token punctuation">(</span><span class="token string">'/some/file/that/does-exist'</span><span class="token punctuation">,</span> errorFirstCallback<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p>The JavaScript <code>try…catch</code> mechanism <strong>cannot</strong> be used to intercept errors
generated by asynchronous APIs. A common mistake for beginners is to try to
use <code>throw</code> inside an error-first callback:</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token comment">// THIS WILL NOT WORK:</span>
<span class="token keyword">const</span> fs <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'fs'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">try</span> <span class="token punctuation">{</span>
  fs<span class="token punctuation">.</span><span class="token function">readFile</span><span class="token punctuation">(</span><span class="token string">'/some/file/that/does-not-exist'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">err<span class="token punctuation">,</span> data</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
    <span class="token comment">// Mistaken assumption: throwing here...</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">throw</span> err<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// This will not catch the throw!</span>
  console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div><p>This will not work because the callback function passed to <code>fs.readFile()</code> is
called asynchronously. By the time the callback has been called, the
surrounding code, including the <code>try…catch</code> block, will have already exited.
Throwing an error inside the callback <strong>can crash the Node.js process</strong> in most
cases. If <a href="/public/blog/node/domain.html">domains</a> are enabled, or a handler has been registered with
<code>process.on('uncaughtException')</code>, such errors can be intercepted.</p> <h2 id="class-error"><a href="#class-error" class="header-anchor">#</a> Class: Error</h2> <p>A generic JavaScript {Error} object that does not denote any specific
circumstance of why the error occurred. <code>Error</code> objects capture a &quot;stack trace&quot;
detailing the point in the code at which the <code>Error</code> was instantiated, and may
provide a text description of the error.</p> <p>All errors generated by Node.js, including all System and JavaScript errors,
will either be instances of, or inherit from, the <code>Error</code> class.</p> <h3 id="new-error-message"><a href="#new-error-message" class="header-anchor">#</a> new Error(message)</h3> <ul><li><code>message</code> {string}</li></ul> <p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the
provided text message. If an object is passed as <code>message</code>, the text message
is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will
represent the point in the code at which <code>new Error()</code> was called. Stack traces
are dependent on <a href="https://github.com/v8/v8/wiki/Stack-Trace-API" target="_blank" rel="noopener noreferrer">V8's stack trace API<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a>. Stack traces extend only to either
(a) the beginning of <em>synchronous code execution</em>, or (b) the number of frames
given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p> <h3 id="error-capturestacktrace-targetobject-constructoropt"><a href="#error-capturestacktrace-targetobject-constructoropt" class="header-anchor">#</a> Error.captureStackTrace(targetObject[, constructorOpt])</h3> <ul><li><code>targetObject</code> {Object}</li> <li><code>constructorOpt</code> {Function}</li></ul> <p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the code at which
<code>Error.captureStackTrace()</code> was called.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> myObject <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
Error<span class="token punctuation">.</span><span class="token function">captureStackTrace</span><span class="token punctuation">(</span>myObject<span class="token punctuation">)</span><span class="token punctuation">;</span>
myObject<span class="token punctuation">.</span>stack<span class="token punctuation">;</span>  <span class="token comment">// Similar to `new Error().stack`</span>
</code></pre></div><p>The first line of the trace will be prefixed with
<code>${myObject.name}: ${myObject.message}</code>.</p> <p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames
above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the
generated stack trace.</p> <p>The <code>constructorOpt</code> argument is useful for hiding implementation
details of error generation from an end user. For instance:</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">function</span> <span class="token function">MyError</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  Error<span class="token punctuation">.</span><span class="token function">captureStackTrace</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> MyError<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token comment">// Without passing MyError to captureStackTrace, the MyError</span>
<span class="token comment">// frame would show up in the .stack property. By passing</span>
<span class="token comment">// the constructor, we omit that frame, and retain all frames below it.</span>
<span class="token keyword">new</span> <span class="token class-name">MyError</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>stack<span class="token punctuation">;</span>
</code></pre></div><h3 id="error-stacktracelimit"><a href="#error-stacktracelimit" class="header-anchor">#</a> Error.stackTraceLimit</h3> <ul><li>{number}</li></ul> <p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames
collected by a stack trace (whether generated by <code>new Error().stack</code> or
<code>Error.captureStackTrace(obj)</code>).</p> <p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes
will affect any stack trace captured <em>after</em> the value has been changed.</p> <p>If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.</p> <h3 id="error-code"><a href="#error-code" class="header-anchor">#</a> error.code</h3> <ul><li>{string}</li></ul> <p>The <code>error.code</code> property is a string label that identifies the kind of error.
<code>error.code</code> is the most stable way to identify an error. It will only change
between major versions of Node.js. In contrast, <code>error.message</code> strings may
change between any versions of Node.js. See <a href="#nodejs-error-codes">Node.js Error Codes</a> for details
about specific codes.</p> <h3 id="error-message"><a href="#error-message" class="header-anchor">#</a> error.message</h3> <ul><li>{string}</li></ul> <p>The <code>error.message</code> property is the string description of the error as set by
calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also
appear in the first line of the stack trace of the <code>Error</code>, however changing
this property after the <code>Error</code> object is created <em>may not</em> change the first
line of the stack trace (for example, when <code>error.stack</code> is read before this
property is changed).</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> err <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'The message'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>err<span class="token punctuation">.</span>message<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Prints: The message</span>
</code></pre></div><h3 id="error-stack"><a href="#error-stack" class="header-anchor">#</a> error.stack</h3> <ul><li>{string}</li></ul> <p>The <code>error.stack</code> property is a string describing the point in the code at which
the <code>Error</code> was instantiated.</p> <div class="language-txt extra-class"><pre class="language-text"><code>Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</code></pre></div><p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and
is followed by a series of stack frames (each line beginning with &quot;at &quot;).
Each frame describes a call site within the code that lead to the error being
generated. V8 attempts to display a name for each function (by variable name,
function name, or object method name), but occasionally it will not be able to
find a suitable name. If V8 cannot determine a name for the function, only
location information will be displayed for that frame. Otherwise, the
determined function name will be displayed with location information appended
in parentheses.</p> <p>Frames are only generated for JavaScript functions. If, for example, execution
synchronously passes through a C++ addon function called <code>cheetahify</code> which
itself calls a JavaScript function, the frame representing the <code>cheetahify</code> call
will not be present in the stack traces:</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> cheetahify <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'./native-binding.node'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">function</span> <span class="token function">makeFaster</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// `cheetahify()` *synchronously* calls speedy.</span>
  <span class="token function">cheetahify</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token function">speedy</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'oh no!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token function">makeFaster</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// will throw:</span>
<span class="token comment">//   /home/gbusey/file.js:6</span>
<span class="token comment">//       throw new Error('oh no!');</span>
<span class="token comment">//           ^</span>
<span class="token comment">//   Error: oh no!</span>
<span class="token comment">//       at speedy (/home/gbusey/file.js:6:11)</span>
<span class="token comment">//       at makeFaster (/home/gbusey/file.js:5:3)</span>
<span class="token comment">//       at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)</span>
<span class="token comment">//       at Module._compile (module.js:456:26)</span>
<span class="token comment">//       at Object.Module._extensions..js (module.js:474:10)</span>
<span class="token comment">//       at Module.load (module.js:356:32)</span>
<span class="token comment">//       at Function.Module._load (module.js:312:12)</span>
<span class="token comment">//       at Function.Module.runMain (module.js:497:10)</span>
<span class="token comment">//       at startup (node.js:119:16)</span>
<span class="token comment">//       at node.js:906:3</span>
</code></pre></div><p>The location information will be one of:</p> <ul><li><code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li> <li><code>plain-filename.js:line:column</code>, if the frame represents a call internal
to Node.js.</li> <li><code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in
a user program, or its dependencies.</li></ul> <p>The string representing the stack trace is lazily generated when the
<code>error.stack</code> property is <strong>accessed</strong>.</p> <p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.</p> <h2 id="class-assertionerror"><a href="#class-assertionerror" class="header-anchor">#</a> Class: AssertionError</h2> <ul><li>Extends: {errors.Error}</li></ul> <p>Indicates the failure of an assertion. For details, see
<a href="/public/blog/node/assert.html#assert_class_assert_assertionerror"><code>Class: assert.AssertionError</code></a>.</p> <h2 id="class-rangeerror"><a href="#class-rangeerror" class="header-anchor">#</a> Class: RangeError</h2> <ul><li>Extends: {errors.Error}</li></ul> <p>Indicates that a provided argument was not within the set or range of
acceptable values for a function; whether that is a numeric range, or
outside the set of options for a given function parameter.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'net'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">connect</span><span class="token punctuation">(</span><span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Throws &quot;RangeError: &quot;port&quot; option should be &gt;= 0 and &lt; 65536: -1&quot;</span>
</code></pre></div><p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form
of argument validation.</p> <h2 id="class-referenceerror"><a href="#class-referenceerror" class="header-anchor">#</a> Class: ReferenceError</h2> <ul><li>Extends: {errors.Error}</li></ul> <p>Indicates that an attempt is being made to access a variable that is not
defined. Such errors commonly indicate typos in code, or an otherwise broken
program.</p> <p>While client code may generate and propagate these errors, in practice, only V8
will do so.</p> <div class="language-js extra-class"><pre class="language-js"><code>doesNotExist<span class="token punctuation">;</span>
<span class="token comment">// Throws ReferenceError, doesNotExist is not a variable in this program.</span>
</code></pre></div><p>Unless an application is dynamically generating and running code,
<code>ReferenceError</code> instances should always be considered a bug in the code
or its dependencies.</p> <h2 id="class-syntaxerror"><a href="#class-syntaxerror" class="header-anchor">#</a> Class: SyntaxError</h2> <ul><li>Extends: {errors.Error}</li></ul> <p>Indicates that a program is not valid JavaScript. These errors may only be
generated and propagated as a result of code evaluation. Code evaluation may
happen as a result of <code>eval</code>, <code>Function</code>, <code>require</code>, or <a href="/public/blog/node/vm.html">vm</a>. These errors
are almost always indicative of a broken program.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">try</span> <span class="token punctuation">{</span>
  <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'vm'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">runInThisContext</span><span class="token punctuation">(</span><span class="token string">'binary ! isNotOk'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>err<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// 'err' will be a SyntaxError.</span>
<span class="token punctuation">}</span>
</code></pre></div><p><code>SyntaxError</code> instances are unrecoverable in the context that created them –
they may only be caught by other contexts.</p> <h2 id="class-systemerror"><a href="#class-systemerror" class="header-anchor">#</a> Class: SystemError</h2> <ul><li>Extends: {errors.Error}</li></ul> <p>Node.js generates system errors when exceptions occur within its runtime
environment. These usually occur when an application violates an operating
system constraint. For example, a system error will occur if an application
attempts to read a file that does not exist.</p> <ul><li><code>address</code> {string} If present, the address to which a network connection
failed</li> <li><code>code</code> {string} The string error code</li> <li><code>dest</code> {string} If present, the file path destination when reporting a file
system error</li> <li><code>errno</code> {number} The system-provided error number</li> <li><code>info</code> {Object} If present, extra details about the error condition</li> <li><code>message</code> {string} A system-provided human-readable description of the error</li> <li><code>path</code> {string} If present, the file path when reporting a file system error</li> <li><code>port</code> {number} If present, the network connection port that is not available</li> <li><code>syscall</code> {string} The name of the system call that triggered the error</li></ul> <h3 id="error-address"><a href="#error-address" class="header-anchor">#</a> error.address</h3> <ul><li>{string}</li></ul> <p>If present, <code>error.address</code> is a string describing the address to which a
network connection failed.</p> <h3 id="error-code-2"><a href="#error-code-2" class="header-anchor">#</a> error.code</h3> <ul><li>{string}</li></ul> <p>The <code>error.code</code> property is a string representing the error code.</p> <h3 id="error-dest"><a href="#error-dest" class="header-anchor">#</a> error.dest</h3> <ul><li>{string}</li></ul> <p>If present, <code>error.dest</code> is the file path destination when reporting a file
system error.</p> <h3 id="error-errno"><a href="#error-errno" class="header-anchor">#</a> error.errno</h3> <ul><li>{number}</li></ul> <p>The <code>error.errno</code> property is a negative number which corresponds
to the error code defined in <a href="http://docs.libuv.org/en/v1.x/errors.html" target="_blank" rel="noopener noreferrer"><code>libuv Error handling</code><svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a>.</p> <p>On Windows the error number provided by the system will be normalized by libuv.</p> <p>To get the string representation of the error code, use
<a href="/public/blog/node/util.html#util_util_getsystemerrorname_err"><code>util.getSystemErrorName(error.errno)</code></a>.</p> <h3 id="error-info"><a href="#error-info" class="header-anchor">#</a> error.info</h3> <ul><li>{Object}</li></ul> <p>If present, <code>error.info</code> is an object with details about the error condition.</p> <h3 id="error-message-2"><a href="#error-message-2" class="header-anchor">#</a> error.message</h3> <ul><li>{string}</li></ul> <p><code>error.message</code> is a system-provided human-readable description of the error.</p> <h3 id="error-path"><a href="#error-path" class="header-anchor">#</a> error.path</h3> <ul><li>{string}</li></ul> <p>If present, <code>error.path</code> is a string containing a relevant invalid pathname.</p> <h3 id="error-port"><a href="#error-port" class="header-anchor">#</a> error.port</h3> <ul><li>{number}</li></ul> <p>If present, <code>error.port</code> is the network connection port that is not available.</p> <h3 id="error-syscall"><a href="#error-syscall" class="header-anchor">#</a> error.syscall</h3> <ul><li>{string}</li></ul> <p>The <code>error.syscall</code> property is a string describing the <a href="http://man7.org/linux/man-pages/man2/syscalls.2.html" target="_blank" rel="noopener noreferrer">syscall<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a> that failed.</p> <h3 id="common-system-errors"><a href="#common-system-errors" class="header-anchor">#</a> Common System Errors</h3> <p>This is a list of system errors commonly-encountered when writing a Node.js
program. For a comprehensive list, see the <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank" rel="noopener noreferrer"><code>errno</code>(3) man page<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a>.</p> <ul><li><p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way
forbidden by its file access permissions.</p></li> <li><p><code>EADDRINUSE</code> (Address already in use): An attempt to bind a server
(<a href="/public/blog/node/net.html"><code>net</code></a>, <a href="/public/blog/node/http.html"><code>http</code></a>, or <a href="/public/blog/node/https.html"><code>https</code></a>) to a local address failed due to
another server on the local system already occupying that address.</p></li> <li><p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the
target machine actively refused it. This usually results from trying to
connect to a service that is inactive on the foreign host.</p></li> <li><p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by
a peer. This normally results from a loss of the connection on the remote
socket due to a timeout or reboot. Commonly encountered via the <a href="/public/blog/node/http.html"><code>http</code></a>
and <a href="/public/blog/node/net.html"><code>net</code></a> modules.</p></li> <li><p><code>EEXIST</code> (File exists): An existing file was the target of an operation that
required that the target not exist.</p></li> <li><p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given
pathname was a directory.</p></li> <li><p><code>EMFILE</code> (Too many open files in system): Maximum number of
<a href="https://en.wikipedia.org/wiki/File_descriptor" target="_blank" rel="noopener noreferrer">file descriptors<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a> allowable on the system has been reached, and
requests for another descriptor cannot be fulfilled until at least one
has been closed. This is encountered when opening many files at once in
parallel, especially on systems (in particular, macOS) where there is a low
file descriptor limit for processes. To remedy a low limit, run
<code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p></li> <li><p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="/public/blog/node/fs.html"><code>fs</code></a> operations
to indicate that a component of the specified pathname does not exist — no
entity (file or directory) could be found by the given path.</p></li> <li><p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but
was not a directory as expected. Commonly raised by <a href="/public/blog/node/fs.html#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p></li> <li><p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target
of an operation that requires an empty directory — usually <a href="/public/blog/node/fs.html#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p></li> <li><p><code>ENOTFOUND</code> (DNS lookup failed): Indicates a DNS failure of either
<code>EAI_NODATA</code> or <code>EAI_NONAME</code>. This is not a standard POSIX error.</p></li> <li><p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an
operation that requires elevated privileges.</p></li> <li><p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is
no process to read the data. Commonly encountered at the <a href="/public/blog/node/net.html"><code>net</code></a> and
<a href="/public/blog/node/http.html"><code>http</code></a> layers, indicative that the remote side of the stream being
written to has been closed.</p></li> <li><p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because
the connected party did not properly respond after a period of time. Usually
encountered by <a href="/public/blog/node/http.html"><code>http</code></a> or <a href="/public/blog/node/net.html"><code>net</code></a> — often a sign that a <code>socket.end()</code>
was not properly called.</p></li></ul> <h2 id="class-typeerror"><a href="#class-typeerror" class="header-anchor">#</a> Class: TypeError</h2> <ul><li>Extends {errors.Error}</li></ul> <p>Indicates that a provided argument is not an allowable type. For example,
passing a function to a parameter which expects a string would be considered
a <code>TypeError</code>.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'url'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Throws TypeError, since it expected a string.</span>
</code></pre></div><p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form
of argument validation.</p> <h2 id="exceptions-vs-errors"><a href="#exceptions-vs-errors" class="header-anchor">#</a> Exceptions vs. Errors</h2> <p>A JavaScript exception is a value that is thrown as a result of an invalid
operation or as the target of a <code>throw</code> statement. While it is not required
that these values are instances of <code>Error</code> or classes which inherit from
<code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be
instances of <code>Error</code>.</p> <p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions
will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code>
checks or <code>abort()</code> calls in the C++ layer.</p> <h2 id="openssl-errors"><a href="#openssl-errors" class="header-anchor">#</a> OpenSSL Errors</h2> <p>Errors originating in <code>crypto</code> or <code>tls</code> are of class <code>Error</code>, and in addition to
the standard <code>.code</code> and <code>.message</code> properties, may have some additional
OpenSSL-specific properties.</p> <h3 id="error-opensslerrorstack"><a href="#error-opensslerrorstack" class="header-anchor">#</a> error.opensslErrorStack</h3> <p>An array of errors that can give context to where in the OpenSSL library an
error originates from.</p> <h3 id="error-function"><a href="#error-function" class="header-anchor">#</a> error.function</h3> <p>The OpenSSL function the error originates in.</p> <h3 id="error-library"><a href="#error-library" class="header-anchor">#</a> error.library</h3> <p>The OpenSSL library the error originates in.</p> <h3 id="error-reason"><a href="#error-reason" class="header-anchor">#</a> error.reason</h3> <p>A human-readable string describing the reason for the error.</p> <p><a id="nodejs-error-codes"></a></p> <h2 id="node-js-error-codes"><a href="#node-js-error-codes" class="header-anchor">#</a> Node.js Error Codes</h2> <p><a id="ERR_AMBIGUOUS_ARGUMENT"></a></p> <h3 id="err-ambiguous-argument"><a href="#err-ambiguous-argument" class="header-anchor">#</a> ERR_AMBIGUOUS_ARGUMENT</h3> <p>A function argument is being used in a way that suggests that the function
signature may be misunderstood. This is thrown by the <code>assert</code> module when the
<code>message</code> parameter in <code>assert.throws(block, message)</code> matches the error message
thrown by <code>block</code> because that usage suggests that the user believes <code>message</code>
is the expected message rather than the message the <code>AssertionError</code> will
display if <code>block</code> does not throw.</p> <p><a id="ERR_ARG_NOT_ITERABLE"></a></p> <h3 id="err-arg-not-iterable"><a href="#err-arg-not-iterable" class="header-anchor">#</a> ERR_ARG_NOT_ITERABLE</h3> <p>An iterable argument (i.e. a value that works with <code>for...of</code> loops) was
required, but not provided to a Node.js API.</p> <p><a id="ERR_ASSERTION"></a></p> <h3 id="err-assertion"><a href="#err-assertion" class="header-anchor">#</a> ERR_ASSERTION</h3> <p>A special type of error that can be triggered whenever Node.js detects an
exceptional logic violation that should never occur. These are raised typically
by the <code>assert</code> module.</p> <p><a id="ERR_ASYNC_CALLBACK"></a></p> <h3 id="err-async-callback"><a href="#err-async-callback" class="header-anchor">#</a> ERR_ASYNC_CALLBACK</h3> <p>An attempt was made to register something that is not a function as an
<code>AsyncHooks</code> callback.</p> <p><a id="ERR_ASYNC_TYPE"></a></p> <h3 id="err-async-type"><a href="#err-async-type" class="header-anchor">#</a> ERR_ASYNC_TYPE</h3> <p>The type of an asynchronous resource was invalid. Users are also able
to define their own types if using the public embedder API.</p> <p><a id="ERR_BROTLI_COMPRESSION_FAILED"></a></p> <h3 id="err-brotli-compression-failed"><a href="#err-brotli-compression-failed" class="header-anchor">#</a> ERR_BROTLI_COMPRESSION_FAILED</h3> <p>Data passed to a Brotli stream was not successfully compressed.</p> <p><a id="ERR_BROTLI_INVALID_PARAM"></a></p> <h3 id="err-brotli-invalid-param"><a href="#err-brotli-invalid-param" class="header-anchor">#</a> ERR_BROTLI_INVALID_PARAM</h3> <p>An invalid parameter key was passed during construction of a Brotli stream.</p> <p><a id="ERR_BUFFER_CONTEXT_NOT_AVAILABLE"></a></p> <h3 id="err-buffer-context-not-available"><a href="#err-buffer-context-not-available" class="header-anchor">#</a> ERR_BUFFER_CONTEXT_NOT_AVAILABLE</h3> <p>An attempt was made to create a Node.js <code>Buffer</code> instance from addon or embedder
code, while in a JS engine Context that is not associated with a Node.js
instance. The data passed to the <code>Buffer</code> method will have been released
by the time the method returns.</p> <p>When encountering this error, a possible alternative to creating a <code>Buffer</code>
instance is to create a normal <code>Uint8Array</code>, which only differs in the
prototype of the resulting object. <code>Uint8Array</code>s are generally accepted in all
Node.js core APIs where <code>Buffer</code>s are; they are available in all Contexts.</p> <p><a id="ERR_BUFFER_OUT_OF_BOUNDS"></a></p> <h3 id="err-buffer-out-of-bounds"><a href="#err-buffer-out-of-bounds" class="header-anchor">#</a> ERR_BUFFER_OUT_OF_BOUNDS</h3> <p>An operation outside the bounds of a <code>Buffer</code> was attempted.</p> <p><a id="ERR_BUFFER_TOO_LARGE"></a></p> <h3 id="err-buffer-too-large"><a href="#err-buffer-too-large" class="header-anchor">#</a> ERR_BUFFER_TOO_LARGE</h3> <p>An attempt has been made to create a <code>Buffer</code> larger than the maximum allowed
size.</p> <p><a id="ERR_CANNOT_WATCH_SIGINT"></a></p> <h3 id="err-cannot-watch-sigint"><a href="#err-cannot-watch-sigint" class="header-anchor">#</a> ERR_CANNOT_WATCH_SIGINT</h3> <p>Node.js was unable to watch for the <code>SIGINT</code> signal.</p> <p><a id="ERR_CHILD_CLOSED_BEFORE_REPLY"></a></p> <h3 id="err-child-closed-before-reply"><a href="#err-child-closed-before-reply" class="header-anchor">#</a> ERR_CHILD_CLOSED_BEFORE_REPLY</h3> <p>A child process was closed before the parent received a reply.</p> <p><a id="ERR_CHILD_PROCESS_IPC_REQUIRED"></a></p> <h3 id="err-child-process-ipc-required"><a href="#err-child-process-ipc-required" class="header-anchor">#</a> ERR_CHILD_PROCESS_IPC_REQUIRED</h3> <p>Used when a child process is being forked without specifying an IPC channel.</p> <p><a id="ERR_CHILD_PROCESS_STDIO_MAXBUFFER"></a></p> <h3 id="err-child-process-stdio-maxbuffer"><a href="#err-child-process-stdio-maxbuffer" class="header-anchor">#</a> ERR_CHILD_PROCESS_STDIO_MAXBUFFER</h3> <p>Used when the main process is trying to read data from the child process's
STDERR/STDOUT, and the data's length is longer than the <code>maxBuffer</code> option.</p> <p><a id="ERR_CONSOLE_WRITABLE_STREAM"></a></p> <h3 id="err-console-writable-stream"><a href="#err-console-writable-stream" class="header-anchor">#</a> ERR_CONSOLE_WRITABLE_STREAM</h3> <p><code>Console</code> was instantiated without <code>stdout</code> stream, or <code>Console</code> has a
non-writable <code>stdout</code> or <code>stderr</code> stream.</p> <p><a id="ERR_CONSTRUCT_CALL_REQUIRED"></a></p> <h3 id="err-construct-call-required"><a href="#err-construct-call-required" class="header-anchor">#</a> ERR_CONSTRUCT_CALL_REQUIRED</h3> <p>A constructor for a class was called without <code>new</code>.</p> <p><a id="ERR_CONSTRUCT_CALL_INVALID"></a></p> <h3 id="err-construct-call-invalid"><a href="#err-construct-call-invalid" class="header-anchor">#</a> ERR_CONSTRUCT_CALL_INVALID</h3> <p>A class constructor was called that is not callable.</p> <p><a id="ERR_CPU_USAGE"></a></p> <h3 id="err-cpu-usage"><a href="#err-cpu-usage" class="header-anchor">#</a> ERR_CPU_USAGE</h3> <p>The native call from <code>process.cpuUsage</code> could not be processed.</p> <p><a id="ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED"></a></p> <h3 id="err-crypto-custom-engine-not-supported"><a href="#err-crypto-custom-engine-not-supported" class="header-anchor">#</a> ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED</h3> <p>A client certificate engine was requested that is not supported by the version
of OpenSSL being used.</p> <p><a id="ERR_CRYPTO_ECDH_INVALID_FORMAT"></a></p> <h3 id="err-crypto-ecdh-invalid-format"><a href="#err-crypto-ecdh-invalid-format" class="header-anchor">#</a> ERR_CRYPTO_ECDH_INVALID_FORMAT</h3> <p>An invalid value for the <code>format</code> argument was passed to the <code>crypto.ECDH()</code>
class <code>getPublicKey()</code> method.</p> <p><a id="ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY"></a></p> <h3 id="err-crypto-ecdh-invalid-public-key"><a href="#err-crypto-ecdh-invalid-public-key" class="header-anchor">#</a> ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY</h3> <p>An invalid value for the <code>key</code> argument has been passed to the
<code>crypto.ECDH()</code> class <code>computeSecret()</code> method. It means that the public
key lies outside of the elliptic curve.</p> <p><a id="ERR_CRYPTO_ENGINE_UNKNOWN"></a></p> <h3 id="err-crypto-engine-unknown"><a href="#err-crypto-engine-unknown" class="header-anchor">#</a> ERR_CRYPTO_ENGINE_UNKNOWN</h3> <p>An invalid crypto engine identifier was passed to
<a href="/public/blog/node/crypto.html#crypto_crypto_setengine_engine_flags"><code>require('crypto').setEngine()</code></a>.</p> <p><a id="ERR_CRYPTO_FIPS_FORCED"></a></p> <h3 id="err-crypto-fips-forced"><a href="#err-crypto-fips-forced" class="header-anchor">#</a> ERR_CRYPTO_FIPS_FORCED</h3> <p>The <a href="/public/blog/node/cli.html#cli_force_fips"><code>--force-fips</code></a> command-line argument was used but there was an attempt
to enable or disable FIPS mode in the <code>crypto</code> module.</p> <p><a id="ERR_CRYPTO_FIPS_UNAVAILABLE"></a></p> <h3 id="err-crypto-fips-unavailable"><a href="#err-crypto-fips-unavailable" class="header-anchor">#</a> ERR_CRYPTO_FIPS_UNAVAILABLE</h3> <p>An attempt was made to enable or disable FIPS mode, but FIPS mode was not
available.</p> <p><a id="ERR_CRYPTO_HASH_FINALIZED"></a></p> <h3 id="err-crypto-hash-finalized"><a href="#err-crypto-hash-finalized" class="header-anchor">#</a> ERR_CRYPTO_HASH_FINALIZED</h3> <p><a href="/public/blog/node/crypto.html#crypto_hash_digest_encoding"><code>hash.digest()</code></a> was called multiple times. The <code>hash.digest()</code> method must
be called no more than one time per instance of a <code>Hash</code> object.</p> <p><a id="ERR_CRYPTO_HASH_UPDATE_FAILED"></a></p> <h3 id="err-crypto-hash-update-failed"><a href="#err-crypto-hash-update-failed" class="header-anchor">#</a> ERR_CRYPTO_HASH_UPDATE_FAILED</h3> <p><a href="/public/blog/node/crypto.html#crypto_hash_update_data_inputencoding"><code>hash.update()</code></a> failed for any reason. This should rarely, if ever, happen.</p> <p><a id="ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS"></a></p> <h3 id="err-crypto-incompatible-key-options"><a href="#err-crypto-incompatible-key-options" class="header-anchor">#</a> ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS</h3> <p>The selected public or private key encoding is incompatible with other options.</p> <p><a id="ERR_CRYPTO_INVALID_DIGEST"></a></p> <h3 id="err-crypto-invalid-digest"><a href="#err-crypto-invalid-digest" class="header-anchor">#</a> ERR_CRYPTO_INVALID_DIGEST</h3> <p>An invalid <a href="/public/blog/node/crypto.html#crypto_crypto_gethashes">crypto digest algorithm</a> was specified.</p> <p><a id="ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE"></a></p> <h3 id="err-crypto-invalid-key-object-type"><a href="#err-crypto-invalid-key-object-type" class="header-anchor">#</a> ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE</h3> <p>The given crypto key object's type is invalid for the attempted operation.</p> <p><a id="ERR_CRYPTO_INVALID_STATE"></a></p> <h3 id="err-crypto-invalid-state"><a href="#err-crypto-invalid-state" class="header-anchor">#</a> ERR_CRYPTO_INVALID_STATE</h3> <p>A crypto method was used on an object that was in an invalid state. For
instance, calling <a href="/public/blog/node/crypto.html#crypto_cipher_getauthtag"><code>cipher.getAuthTag()</code></a> before calling <code>cipher.final()</code>.</p> <p><a id="ERR_CRYPTO_PBKDF2_ERROR"></a></p> <h3 id="err-crypto-pbkdf2-error"><a href="#err-crypto-pbkdf2-error" class="header-anchor">#</a> ERR_CRYPTO_PBKDF2_ERROR</h3> <p>The PBKDF2 algorithm failed for unspecified reasons. OpenSSL does not provide
more details and therefore neither does Node.js.</p> <p><a id="ERR_CRYPTO_SCRYPT_INVALID_PARAMETER"></a></p> <h3 id="err-crypto-scrypt-invalid-parameter"><a href="#err-crypto-scrypt-invalid-parameter" class="header-anchor">#</a> ERR_CRYPTO_SCRYPT_INVALID_PARAMETER</h3> <p>One or more <a href="/public/blog/node/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback"><code>crypto.scrypt()</code></a> or <a href="/public/blog/node/crypto.html#crypto_crypto_scryptsync_password_salt_keylen_options"><code>crypto.scryptSync()</code></a> parameters are
outside their legal range.</p> <p><a id="ERR_CRYPTO_SCRYPT_NOT_SUPPORTED"></a></p> <h3 id="err-crypto-scrypt-not-supported"><a href="#err-crypto-scrypt-not-supported" class="header-anchor">#</a> ERR_CRYPTO_SCRYPT_NOT_SUPPORTED</h3> <p>Node.js was compiled without <code>scrypt</code> support. Not possible with the official
release binaries but can happen with custom builds, including distro builds.</p> <p><a id="ERR_CRYPTO_SIGN_KEY_REQUIRED"></a></p> <h3 id="err-crypto-sign-key-required"><a href="#err-crypto-sign-key-required" class="header-anchor">#</a> ERR_CRYPTO_SIGN_KEY_REQUIRED</h3> <p>A signing <code>key</code> was not provided to the <a href="/public/blog/node/crypto.html#crypto_sign_sign_privatekey_outputencoding"><code>sign.sign()</code></a> method.</p> <p><a id="ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH"></a></p> <h3 id="err-crypto-timing-safe-equal-length"><a href="#err-crypto-timing-safe-equal-length" class="header-anchor">#</a> ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH</h3> <p><a href="/public/blog/node/crypto.html#crypto_crypto_timingsafeequal_a_b"><code>crypto.timingSafeEqual()</code></a> was called with <code>Buffer</code>, <code>TypedArray</code>, or
<code>DataView</code> arguments of different lengths.</p> <p><a id="ERR_DIR_CLOSED"></a></p> <h3 id="err-dir-closed"><a href="#err-dir-closed" class="header-anchor">#</a> ERR_DIR_CLOSED</h3> <p>The <a href="/public/blog/node/fs.html#fs_class_fs_dir"><code>fs.Dir</code></a> was previously closed.</p> <p><a id="ERR_DNS_SET_SERVERS_FAILED"></a></p> <h3 id="err-dns-set-servers-failed"><a href="#err-dns-set-servers-failed" class="header-anchor">#</a> ERR_DNS_SET_SERVERS_FAILED</h3> <p><code>c-ares</code> failed to set the DNS server.</p> <p><a id="ERR_DOMAIN_CALLBACK_NOT_AVAILABLE"></a></p> <h3 id="err-domain-callback-not-available"><a href="#err-domain-callback-not-available" class="header-anchor">#</a> ERR_DOMAIN_CALLBACK_NOT_AVAILABLE</h3> <p>The <code>domain</code> module was not usable since it could not establish the required
error handling hooks, because
<a href="/public/blog/node/process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> had been called at an
earlier point in time.</p> <p><a id="ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE"></a></p> <h3 id="err-domain-cannot-set-uncaught-exception-capture"><a href="#err-domain-cannot-set-uncaught-exception-capture" class="header-anchor">#</a> ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE</h3> <p><a href="/public/blog/node/process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> could not be called
because the <code>domain</code> module has been loaded at an earlier point in time.</p> <p>The stack trace is extended to include the point in time at which the
<code>domain</code> module had been loaded.</p> <p><a id="ERR_ENCODING_INVALID_ENCODED_DATA"></a></p> <h3 id="err-encoding-invalid-encoded-data"><a href="#err-encoding-invalid-encoded-data" class="header-anchor">#</a> ERR_ENCODING_INVALID_ENCODED_DATA</h3> <p>Data provided to <code>TextDecoder()</code> API was invalid according to the encoding
provided.</p> <p><a id="ERR_ENCODING_NOT_SUPPORTED"></a></p> <h3 id="err-encoding-not-supported"><a href="#err-encoding-not-supported" class="header-anchor">#</a> ERR_ENCODING_NOT_SUPPORTED</h3> <p>Encoding provided to <code>TextDecoder()</code> API was not one of the
<a href="/public/blog/node/util.html#util_whatwg_supported_encodings">WHATWG Supported Encodings</a>.</p> <p><a id="ERR_FALSY_VALUE_REJECTION"></a></p> <h3 id="err-falsy-value-rejection"><a href="#err-falsy-value-rejection" class="header-anchor">#</a> ERR_FALSY_VALUE_REJECTION</h3> <p>A <code>Promise</code> that was callbackified via <code>util.callbackify()</code> was rejected with a
falsy value.</p> <p><a id="ERR_FS_FILE_TOO_LARGE"></a></p> <h3 id="err-fs-file-too-large"><a href="#err-fs-file-too-large" class="header-anchor">#</a> ERR_FS_FILE_TOO_LARGE</h3> <p>An attempt has been made to read a file whose size is larger than the maximum
allowed size for a <code>Buffer</code>.</p> <p><a id="ERR_FS_INVALID_SYMLINK_TYPE"></a></p> <h3 id="err-fs-invalid-symlink-type"><a href="#err-fs-invalid-symlink-type" class="header-anchor">#</a> ERR_FS_INVALID_SYMLINK_TYPE</h3> <p>An invalid symlink type was passed to the <a href="/public/blog/node/fs.html#fs_fs_symlink_target_path_type_callback"><code>fs.symlink()</code></a> or
<a href="/public/blog/node/fs.html#fs_fs_symlinksync_target_path_type"><code>fs.symlinkSync()</code></a> methods.</p> <p><a id="ERR_HTTP_HEADERS_SENT"></a></p> <h3 id="err-http-headers-sent"><a href="#err-http-headers-sent" class="header-anchor">#</a> ERR_HTTP_HEADERS_SENT</h3> <p>An attempt was made to add more headers after the headers had already been sent.</p> <p><a id="ERR_HTTP_INVALID_HEADER_VALUE"></a></p> <h3 id="err-http-invalid-header-value"><a href="#err-http-invalid-header-value" class="header-anchor">#</a> ERR_HTTP_INVALID_HEADER_VALUE</h3> <p>An invalid HTTP header value was specified.</p> <p><a id="ERR_HTTP_INVALID_STATUS_CODE"></a></p> <h3 id="err-http-invalid-status-code"><a href="#err-http-invalid-status-code" class="header-anchor">#</a> ERR_HTTP_INVALID_STATUS_CODE</h3> <p>Status code was outside the regular status code range (100-999).</p> <p><a id="ERR_HTTP_TRAILER_INVALID"></a></p> <h3 id="err-http-trailer-invalid"><a href="#err-http-trailer-invalid" class="header-anchor">#</a> ERR_HTTP_TRAILER_INVALID</h3> <p>The <code>Trailer</code> header was set even though the transfer encoding does not support
that.</p> <p><a id="ERR_HTTP2_ALTSVC_INVALID_ORIGIN"></a></p> <h3 id="err-http2-altsvc-invalid-origin"><a href="#err-http2-altsvc-invalid-origin" class="header-anchor">#</a> ERR_HTTP2_ALTSVC_INVALID_ORIGIN</h3> <p>HTTP/2 ALTSVC frames require a valid origin.</p> <p><a id="ERR_HTTP2_ALTSVC_LENGTH"></a></p> <h3 id="err-http2-altsvc-length"><a href="#err-http2-altsvc-length" class="header-anchor">#</a> ERR_HTTP2_ALTSVC_LENGTH</h3> <p>HTTP/2 ALTSVC frames are limited to a maximum of 16,382 payload bytes.</p> <p><a id="ERR_HTTP2_CONNECT_AUTHORITY"></a></p> <h3 id="err-http2-connect-authority"><a href="#err-http2-connect-authority" class="header-anchor">#</a> ERR_HTTP2_CONNECT_AUTHORITY</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:authority</code> pseudo-header
is required.</p> <p><a id="ERR_HTTP2_CONNECT_PATH"></a></p> <h3 id="err-http2-connect-path"><a href="#err-http2-connect-path" class="header-anchor">#</a> ERR_HTTP2_CONNECT_PATH</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:path</code> pseudo-header is
forbidden.</p> <p><a id="ERR_HTTP2_CONNECT_SCHEME"></a></p> <h3 id="err-http2-connect-scheme"><a href="#err-http2-connect-scheme" class="header-anchor">#</a> ERR_HTTP2_CONNECT_SCHEME</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:scheme</code> pseudo-header is
forbidden.</p> <p><a id="ERR_HTTP2_ERROR"></a></p> <h3 id="err-http2-error"><a href="#err-http2-error" class="header-anchor">#</a> ERR_HTTP2_ERROR</h3> <p>A non-specific HTTP/2 error has occurred.</p> <p><a id="ERR_HTTP2_GOAWAY_SESSION"></a></p> <h3 id="err-http2-goaway-session"><a href="#err-http2-goaway-session" class="header-anchor">#</a> ERR_HTTP2_GOAWAY_SESSION</h3> <p>New HTTP/2 Streams may not be opened after the <code>Http2Session</code> has received a
<code>GOAWAY</code> frame from the connected peer.</p> <p><a id="ERR_HTTP2_HEADERS_AFTER_RESPOND"></a></p> <h3 id="err-http2-headers-after-respond"><a href="#err-http2-headers-after-respond" class="header-anchor">#</a> ERR_HTTP2_HEADERS_AFTER_RESPOND</h3> <p>An additional headers was specified after an HTTP/2 response was initiated.</p> <p><a id="ERR_HTTP2_HEADERS_SENT"></a></p> <h3 id="err-http2-headers-sent"><a href="#err-http2-headers-sent" class="header-anchor">#</a> ERR_HTTP2_HEADERS_SENT</h3> <p>An attempt was made to send multiple response headers.</p> <p><a id="ERR_HTTP2_HEADER_SINGLE_VALUE"></a></p> <h3 id="err-http2-header-single-value"><a href="#err-http2-header-single-value" class="header-anchor">#</a> ERR_HTTP2_HEADER_SINGLE_VALUE</h3> <p>Multiple values were provided for an HTTP/2 header field that was required to
have only a single value.</p> <p><a id="ERR_HTTP2_INFO_STATUS_NOT_ALLOWED"></a></p> <h3 id="err-http2-info-status-not-allowed"><a href="#err-http2-info-status-not-allowed" class="header-anchor">#</a> ERR_HTTP2_INFO_STATUS_NOT_ALLOWED</h3> <p>Informational HTTP status codes (<code>1xx</code>) may not be set as the response status
code on HTTP/2 responses.</p> <p><a id="ERR_HTTP2_INVALID_CONNECTION_HEADERS"></a></p> <h3 id="err-http2-invalid-connection-headers"><a href="#err-http2-invalid-connection-headers" class="header-anchor">#</a> ERR_HTTP2_INVALID_CONNECTION_HEADERS</h3> <p>HTTP/1 connection specific headers are forbidden to be used in HTTP/2
requests and responses.</p> <p><a id="ERR_HTTP2_INVALID_HEADER_VALUE"></a></p> <h3 id="err-http2-invalid-header-value"><a href="#err-http2-invalid-header-value" class="header-anchor">#</a> ERR_HTTP2_INVALID_HEADER_VALUE</h3> <p>An invalid HTTP/2 header value was specified.</p> <p><a id="ERR_HTTP2_INVALID_INFO_STATUS"></a></p> <h3 id="err-http2-invalid-info-status"><a href="#err-http2-invalid-info-status" class="header-anchor">#</a> ERR_HTTP2_INVALID_INFO_STATUS</h3> <p>An invalid HTTP informational status code has been specified. Informational
status codes must be an integer between <code>100</code> and <code>199</code> (inclusive).</p> <p><a id="ERR_HTTP2_INVALID_ORIGIN"></a></p> <h3 id="err-http2-invalid-origin"><a href="#err-http2-invalid-origin" class="header-anchor">#</a> ERR_HTTP2_INVALID_ORIGIN</h3> <p>HTTP/2 <code>ORIGIN</code> frames require a valid origin.</p> <p><a id="ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH"></a></p> <h3 id="err-http2-invalid-packed-settings-length"><a href="#err-http2-invalid-packed-settings-length" class="header-anchor">#</a> ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH</h3> <p>Input <code>Buffer</code> and <code>Uint8Array</code> instances passed to the
<code>http2.getUnpackedSettings()</code> API must have a length that is a multiple of
six.</p> <p><a id="ERR_HTTP2_INVALID_PSEUDOHEADER"></a></p> <h3 id="err-http2-invalid-pseudoheader"><a href="#err-http2-invalid-pseudoheader" class="header-anchor">#</a> ERR_HTTP2_INVALID_PSEUDOHEADER</h3> <p>Only valid HTTP/2 pseudoheaders (<code>:status</code>, <code>:path</code>, <code>:authority</code>, <code>:scheme</code>,
and <code>:method</code>) may be used.</p> <p><a id="ERR_HTTP2_INVALID_SESSION"></a></p> <h3 id="err-http2-invalid-session"><a href="#err-http2-invalid-session" class="header-anchor">#</a> ERR_HTTP2_INVALID_SESSION</h3> <p>An action was performed on an <code>Http2Session</code> object that had already been
destroyed.</p> <p><a id="ERR_HTTP2_INVALID_SETTING_VALUE"></a></p> <h3 id="err-http2-invalid-setting-value"><a href="#err-http2-invalid-setting-value" class="header-anchor">#</a> ERR_HTTP2_INVALID_SETTING_VALUE</h3> <p>An invalid value has been specified for an HTTP/2 setting.</p> <p><a id="ERR_HTTP2_INVALID_STREAM"></a></p> <h3 id="err-http2-invalid-stream"><a href="#err-http2-invalid-stream" class="header-anchor">#</a> ERR_HTTP2_INVALID_STREAM</h3> <p>An operation was performed on a stream that had already been destroyed.</p> <p><a id="ERR_HTTP2_MAX_PENDING_SETTINGS_ACK"></a></p> <h3 id="err-http2-max-pending-settings-ack"><a href="#err-http2-max-pending-settings-ack" class="header-anchor">#</a> ERR_HTTP2_MAX_PENDING_SETTINGS_ACK</h3> <p>Whenever an HTTP/2 <code>SETTINGS</code> frame is sent to a connected peer, the peer is
required to send an acknowledgment that it has received and applied the new
<code>SETTINGS</code>. By default, a maximum number of unacknowledged <code>SETTINGS</code> frames may
be sent at any given time. This error code is used when that limit has been
reached.</p> <p><a id="ERR_HTTP2_NESTED_PUSH"></a></p> <h3 id="err-http2-nested-push"><a href="#err-http2-nested-push" class="header-anchor">#</a> ERR_HTTP2_NESTED_PUSH</h3> <p>An attempt was made to initiate a new push stream from within a push stream.
Nested push streams are not permitted.</p> <p><a id="ERR_HTTP2_NO_SOCKET_MANIPULATION"></a></p> <h3 id="err-http2-no-socket-manipulation"><a href="#err-http2-no-socket-manipulation" class="header-anchor">#</a> ERR_HTTP2_NO_SOCKET_MANIPULATION</h3> <p>An attempt was made to directly manipulate (read, write, pause, resume, etc.) a
socket attached to an <code>Http2Session</code>.</p> <p><a id="ERR_HTTP2_ORIGIN_LENGTH"></a></p> <h3 id="err-http2-origin-length"><a href="#err-http2-origin-length" class="header-anchor">#</a> ERR_HTTP2_ORIGIN_LENGTH</h3> <p>HTTP/2 <code>ORIGIN</code> frames are limited to a length of 16382 bytes.</p> <p><a id="ERR_HTTP2_OUT_OF_STREAMS"></a></p> <h3 id="err-http2-out-of-streams"><a href="#err-http2-out-of-streams" class="header-anchor">#</a> ERR_HTTP2_OUT_OF_STREAMS</h3> <p>The number of streams created on a single HTTP/2 session reached the maximum
limit.</p> <p><a id="ERR_HTTP2_PAYLOAD_FORBIDDEN"></a></p> <h3 id="err-http2-payload-forbidden"><a href="#err-http2-payload-forbidden" class="header-anchor">#</a> ERR_HTTP2_PAYLOAD_FORBIDDEN</h3> <p>A message payload was specified for an HTTP response code for which a payload is
forbidden.</p> <p><a id="ERR_HTTP2_PING_CANCEL"></a></p> <h3 id="err-http2-ping-cancel"><a href="#err-http2-ping-cancel" class="header-anchor">#</a> ERR_HTTP2_PING_CANCEL</h3> <p>An HTTP/2 ping was canceled.</p> <p><a id="ERR_HTTP2_PING_LENGTH"></a></p> <h3 id="err-http2-ping-length"><a href="#err-http2-ping-length" class="header-anchor">#</a> ERR_HTTP2_PING_LENGTH</h3> <p>HTTP/2 ping payloads must be exactly 8 bytes in length.</p> <p><a id="ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED"></a></p> <h3 id="err-http2-pseudoheader-not-allowed"><a href="#err-http2-pseudoheader-not-allowed" class="header-anchor">#</a> ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED</h3> <p>An HTTP/2 pseudo-header has been used inappropriately. Pseudo-headers are header
key names that begin with the <code>:</code> prefix.</p> <p><a id="ERR_HTTP2_PUSH_DISABLED"></a></p> <h3 id="err-http2-push-disabled"><a href="#err-http2-push-disabled" class="header-anchor">#</a> ERR_HTTP2_PUSH_DISABLED</h3> <p>An attempt was made to create a push stream, which had been disabled by the
client.</p> <p><a id="ERR_HTTP2_SEND_FILE"></a></p> <h3 id="err-http2-send-file"><a href="#err-http2-send-file" class="header-anchor">#</a> ERR_HTTP2_SEND_FILE</h3> <p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to
send a directory.</p> <p><a id="ERR_HTTP2_SEND_FILE_NOSEEK"></a></p> <h3 id="err-http2-send-file-noseek"><a href="#err-http2-send-file-noseek" class="header-anchor">#</a> ERR_HTTP2_SEND_FILE_NOSEEK</h3> <p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to
send something other than a regular file, but <code>offset</code> or <code>length</code> options were
provided.</p> <p><a id="ERR_HTTP2_SESSION_ERROR"></a></p> <h3 id="err-http2-session-error"><a href="#err-http2-session-error" class="header-anchor">#</a> ERR_HTTP2_SESSION_ERROR</h3> <p>The <code>Http2Session</code> closed with a non-zero error code.</p> <p><a id="ERR_HTTP2_SETTINGS_CANCEL"></a></p> <h3 id="err-http2-settings-cancel"><a href="#err-http2-settings-cancel" class="header-anchor">#</a> ERR_HTTP2_SETTINGS_CANCEL</h3> <p>The <code>Http2Session</code> settings canceled.</p> <p><a id="ERR_HTTP2_SOCKET_BOUND"></a></p> <h3 id="err-http2-socket-bound"><a href="#err-http2-socket-bound" class="header-anchor">#</a> ERR_HTTP2_SOCKET_BOUND</h3> <p>An attempt was made to connect a <code>Http2Session</code> object to a <code>net.Socket</code> or
<code>tls.TLSSocket</code> that had already been bound to another <code>Http2Session</code> object.</p> <p><a id="ERR_HTTP2_SOCKET_UNBOUND"></a></p> <h3 id="err-http2-socket-unbound"><a href="#err-http2-socket-unbound" class="header-anchor">#</a> ERR_HTTP2_SOCKET_UNBOUND</h3> <p>An attempt was made to use the <code>socket</code> property of an <code>Http2Session</code> that
has already been closed.</p> <p><a id="ERR_HTTP2_STATUS_101"></a></p> <h3 id="err-http2-status-101"><a href="#err-http2-status-101" class="header-anchor">#</a> ERR_HTTP2_STATUS_101</h3> <p>Use of the <code>101</code> Informational status code is forbidden in HTTP/2.</p> <p><a id="ERR_HTTP2_STATUS_INVALID"></a></p> <h3 id="err-http2-status-invalid"><a href="#err-http2-status-invalid" class="header-anchor">#</a> ERR_HTTP2_STATUS_INVALID</h3> <p>An invalid HTTP status code has been specified. Status codes must be an integer
between <code>100</code> and <code>599</code> (inclusive).</p> <p><a id="ERR_HTTP2_STREAM_CANCEL"></a></p> <h3 id="err-http2-stream-cancel"><a href="#err-http2-stream-cancel" class="header-anchor">#</a> ERR_HTTP2_STREAM_CANCEL</h3> <p>An <code>Http2Stream</code> was destroyed before any data was transmitted to the connected
peer.</p> <p><a id="ERR_HTTP2_STREAM_ERROR"></a></p> <h3 id="err-http2-stream-error"><a href="#err-http2-stream-error" class="header-anchor">#</a> ERR_HTTP2_STREAM_ERROR</h3> <p>A non-zero error code was been specified in an <code>RST_STREAM</code> frame.</p> <p><a id="ERR_HTTP2_STREAM_SELF_DEPENDENCY"></a></p> <h3 id="err-http2-stream-self-dependency"><a href="#err-http2-stream-self-dependency" class="header-anchor">#</a> ERR_HTTP2_STREAM_SELF_DEPENDENCY</h3> <p>When setting the priority for an HTTP/2 stream, the stream may be marked as
a dependency for a parent stream. This error code is used when an attempt is
made to mark a stream and dependent of itself.</p> <p><a id="ERR_HTTP2_TRAILERS_ALREADY_SENT"></a></p> <h3 id="err-http2-trailers-already-sent"><a href="#err-http2-trailers-already-sent" class="header-anchor">#</a> ERR_HTTP2_TRAILERS_ALREADY_SENT</h3> <p>Trailing headers have already been sent on the <code>Http2Stream</code>.</p> <p><a id="ERR_HTTP2_TRAILERS_NOT_READY"></a></p> <h3 id="err-http2-trailers-not-ready"><a href="#err-http2-trailers-not-ready" class="header-anchor">#</a> ERR_HTTP2_TRAILERS_NOT_READY</h3> <p>The <code>http2stream.sendTrailers()</code> method cannot be called until after the
<code>'wantTrailers'</code> event is emitted on an <code>Http2Stream</code> object. The
<code>'wantTrailers'</code> event will only be emitted if the <code>waitForTrailers</code> option
is set for the <code>Http2Stream</code>.</p> <p><a id="ERR_HTTP2_UNSUPPORTED_PROTOCOL"></a></p> <h3 id="err-http2-unsupported-protocol"><a href="#err-http2-unsupported-protocol" class="header-anchor">#</a> ERR_HTTP2_UNSUPPORTED_PROTOCOL</h3> <p><code>http2.connect()</code> was passed a URL that uses any protocol other than <code>http:</code> or
<code>https:</code>.</p> <p><a id="ERR_INTERNAL_ASSERTION"></a></p> <h3 id="err-internal-assertion"><a href="#err-internal-assertion" class="header-anchor">#</a> ERR_INTERNAL_ASSERTION</h3> <p>There was a bug in Node.js or incorrect usage of Node.js internals.
To fix the error, open an issue at https://github.com/nodejs/node/issues.</p> <p><a id="ERR_INCOMPATIBLE_OPTION_PAIR"></a></p> <h3 id="err-incompatible-option-pair"><a href="#err-incompatible-option-pair" class="header-anchor">#</a> ERR_INCOMPATIBLE_OPTION_PAIR</h3> <p>An option pair is incompatible with each other and can not be used at the same
time.</p> <p><a id="ERR_INPUT_TYPE_NOT_ALLOWED"></a></p> <h3 id="err-input-type-not-allowed"><a href="#err-input-type-not-allowed" class="header-anchor">#</a> ERR_INPUT_TYPE_NOT_ALLOWED</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>The <code>--input-type</code> flag was used to attempt to execute a file. This flag can
only be used with input via <code>--eval</code>, <code>--print</code> or <code>STDIN</code>.</p> <p><a id="ERR_INSPECTOR_ALREADY_CONNECTED"></a></p> <h3 id="err-inspector-already-connected"><a href="#err-inspector-already-connected" class="header-anchor">#</a> ERR_INSPECTOR_ALREADY_CONNECTED</h3> <p>While using the <code>inspector</code> module, an attempt was made to connect when the
inspector was already connected.</p> <p><a id="ERR_INSPECTOR_CLOSED"></a></p> <h3 id="err-inspector-closed"><a href="#err-inspector-closed" class="header-anchor">#</a> ERR_INSPECTOR_CLOSED</h3> <p>While using the <code>inspector</code> module, an attempt was made to use the inspector
after the session had already closed.</p> <p><a id="ERR_INSPECTOR_COMMAND"></a></p> <h3 id="err-inspector-command"><a href="#err-inspector-command" class="header-anchor">#</a> ERR_INSPECTOR_COMMAND</h3> <p>An error occurred while issuing a command via the <code>inspector</code> module.</p> <p><a id="ERR_INSPECTOR_NOT_ACTIVE"></a></p> <h3 id="err-inspector-not-active"><a href="#err-inspector-not-active" class="header-anchor">#</a> ERR_INSPECTOR_NOT_ACTIVE</h3> <p>The <code>inspector</code> is not active when <code>inspector.waitForDebugger()</code> is called.</p> <p><a id="ERR_INSPECTOR_NOT_AVAILABLE"></a></p> <h3 id="err-inspector-not-available"><a href="#err-inspector-not-available" class="header-anchor">#</a> ERR_INSPECTOR_NOT_AVAILABLE</h3> <p>The <code>inspector</code> module is not available for use.</p> <p><a id="ERR_INSPECTOR_NOT_CONNECTED"></a></p> <h3 id="err-inspector-not-connected"><a href="#err-inspector-not-connected" class="header-anchor">#</a> ERR_INSPECTOR_NOT_CONNECTED</h3> <p>While using the <code>inspector</code> module, an attempt was made to use the inspector
before it was connected.</p> <p><a id="ERR_INSPECTOR_NOT_WORKER"></a></p> <h3 id="err-inspector-not-worker"><a href="#err-inspector-not-worker" class="header-anchor">#</a> ERR_INSPECTOR_NOT_WORKER</h3> <p>An API was called on the main thread that can only be used from
the worker thread.</p> <p><a id="ERR_INVALID_ADDRESS_FAMILY"></a></p> <h3 id="err-invalid-address-family"><a href="#err-invalid-address-family" class="header-anchor">#</a> ERR_INVALID_ADDRESS_FAMILY</h3> <p>The provided address family is not understood by the Node.js API.</p> <p><a id="ERR_INVALID_ARG_TYPE"></a></p> <h3 id="err-invalid-arg-type"><a href="#err-invalid-arg-type" class="header-anchor">#</a> ERR_INVALID_ARG_TYPE</h3> <p>An argument of the wrong type was passed to a Node.js API.</p> <p><a id="ERR_INVALID_ARG_VALUE"></a></p> <h3 id="err-invalid-arg-value"><a href="#err-invalid-arg-value" class="header-anchor">#</a> ERR_INVALID_ARG_VALUE</h3> <p>An invalid or unsupported value was passed for a given argument.</p> <p><a id="ERR_INVALID_ASYNC_ID"></a></p> <h3 id="err-invalid-async-id"><a href="#err-invalid-async-id" class="header-anchor">#</a> ERR_INVALID_ASYNC_ID</h3> <p>An invalid <code>asyncId</code> or <code>triggerAsyncId</code> was passed using <code>AsyncHooks</code>. An id
less than -1 should never happen.</p> <p><a id="ERR_INVALID_BUFFER_SIZE"></a></p> <h3 id="err-invalid-buffer-size"><a href="#err-invalid-buffer-size" class="header-anchor">#</a> ERR_INVALID_BUFFER_SIZE</h3> <p>A swap was performed on a <code>Buffer</code> but its size was not compatible with the
operation.</p> <p><a id="ERR_INVALID_CALLBACK"></a></p> <h3 id="err-invalid-callback"><a href="#err-invalid-callback" class="header-anchor">#</a> ERR_INVALID_CALLBACK</h3> <p>A callback function was required but was not been provided to a Node.js API.</p> <p><a id="ERR_INVALID_CHAR"></a></p> <h3 id="err-invalid-char"><a href="#err-invalid-char" class="header-anchor">#</a> ERR_INVALID_CHAR</h3> <p>Invalid characters were detected in headers.</p> <p><a id="ERR_INVALID_CURSOR_POS"></a></p> <h3 id="err-invalid-cursor-pos"><a href="#err-invalid-cursor-pos" class="header-anchor">#</a> ERR_INVALID_CURSOR_POS</h3> <p>A cursor on a given stream cannot be moved to a specified row without a
specified column.</p> <p><a id="ERR_INVALID_FD"></a></p> <h3 id="err-invalid-fd"><a href="#err-invalid-fd" class="header-anchor">#</a> ERR_INVALID_FD</h3> <p>A file descriptor ('fd') was not valid (e.g. it was a negative value).</p> <p><a id="ERR_INVALID_FD_TYPE"></a></p> <h3 id="err-invalid-fd-type"><a href="#err-invalid-fd-type" class="header-anchor">#</a> ERR_INVALID_FD_TYPE</h3> <p>A file descriptor ('fd') type was not valid.</p> <p><a id="ERR_INVALID_FILE_URL_HOST"></a></p> <h3 id="err-invalid-file-url-host"><a href="#err-invalid-file-url-host" class="header-anchor">#</a> ERR_INVALID_FILE_URL_HOST</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the
<a href="/public/blog/node/fs.html"><code>fs</code></a> module) encountered a file URL with an incompatible host. This
situation can only occur on Unix-like systems where only <code>localhost</code> or an empty
host is supported.</p> <p><a id="ERR_INVALID_FILE_URL_PATH"></a></p> <h3 id="err-invalid-file-url-path"><a href="#err-invalid-file-url-path" class="header-anchor">#</a> ERR_INVALID_FILE_URL_PATH</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the
<a href="/public/blog/node/fs.html"><code>fs</code></a> module) encountered a file URL with an incompatible path. The exact
semantics for determining whether a path can be used is platform-dependent.</p> <p><a id="ERR_INVALID_HANDLE_TYPE"></a></p> <h3 id="err-invalid-handle-type"><a href="#err-invalid-handle-type" class="header-anchor">#</a> ERR_INVALID_HANDLE_TYPE</h3> <p>An attempt was made to send an unsupported &quot;handle&quot; over an IPC communication
channel to a child process. See <a href="/public/blog/node/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback"><code>subprocess.send()</code></a> and <a href="/public/blog/node/process.html#process_process_send_message_sendhandle_options_callback"><code>process.send()</code></a>
for more information.</p> <p><a id="ERR_INVALID_HTTP_TOKEN"></a></p> <h3 id="err-invalid-http-token"><a href="#err-invalid-http-token" class="header-anchor">#</a> ERR_INVALID_HTTP_TOKEN</h3> <p>An invalid HTTP token was supplied.</p> <p><a id="ERR_INVALID_IP_ADDRESS"></a></p> <h3 id="err-invalid-ip-address"><a href="#err-invalid-ip-address" class="header-anchor">#</a> ERR_INVALID_IP_ADDRESS</h3> <p>An IP address is not valid.</p> <p><a id="ERR_INVALID_OPT_VALUE"></a></p> <h3 id="err-invalid-opt-value"><a href="#err-invalid-opt-value" class="header-anchor">#</a> ERR_INVALID_OPT_VALUE</h3> <p>An invalid or unexpected value was passed in an options object.</p> <p><a id="ERR_INVALID_OPT_VALUE_ENCODING"></a></p> <h3 id="err-invalid-opt-value-encoding"><a href="#err-invalid-opt-value-encoding" class="header-anchor">#</a> ERR_INVALID_OPT_VALUE_ENCODING</h3> <p>An invalid or unknown file encoding was passed.</p> <p><a id="ERR_INVALID_PACKAGE_CONFIG"></a></p> <h3 id="err-invalid-package-config"><a href="#err-invalid-package-config" class="header-anchor">#</a> ERR_INVALID_PACKAGE_CONFIG</h3> <p>An invalid <code>package.json</code> file was found which failed parsing.</p> <p><a id="ERR_INVALID_PERFORMANCE_MARK"></a></p> <h3 id="err-invalid-performance-mark"><a href="#err-invalid-performance-mark" class="header-anchor">#</a> ERR_INVALID_PERFORMANCE_MARK</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), a performance mark is
invalid.</p> <p><a id="ERR_INVALID_PROTOCOL"></a></p> <h3 id="err-invalid-protocol"><a href="#err-invalid-protocol" class="header-anchor">#</a> ERR_INVALID_PROTOCOL</h3> <p>An invalid <code>options.protocol</code> was passed to <code>http.request()</code>.</p> <p><a id="ERR_INVALID_REPL_EVAL_CONFIG"></a></p> <h3 id="err-invalid-repl-eval-config"><a href="#err-invalid-repl-eval-config" class="header-anchor">#</a> ERR_INVALID_REPL_EVAL_CONFIG</h3> <p>Both <code>breakEvalOnSigint</code> and <code>eval</code> options were set in the <a href="/public/blog/node/repl.html"><code>REPL</code></a> config,
which is not supported.</p> <p><a id="ERR_INVALID_REPL_INPUT"></a></p> <h3 id="err-invalid-repl-input"><a href="#err-invalid-repl-input" class="header-anchor">#</a> ERR_INVALID_REPL_INPUT</h3> <p>The input may not be used in the <a href="/public/blog/node/repl.html"><code>REPL</code></a>. All prohibited inputs are
documented in the <a href="/public/blog/node/repl.html"><code>REPL</code></a>'s documentation.</p> <p><a id="ERR_INVALID_RETURN_PROPERTY"></a></p> <h3 id="err-invalid-return-property"><a href="#err-invalid-return-property" class="header-anchor">#</a> ERR_INVALID_RETURN_PROPERTY</h3> <p>Thrown in case a function option does not provide a valid value for one of its
returned object properties on execution.</p> <p><a id="ERR_INVALID_RETURN_PROPERTY_VALUE"></a></p> <h3 id="err-invalid-return-property-value"><a href="#err-invalid-return-property-value" class="header-anchor">#</a> ERR_INVALID_RETURN_PROPERTY_VALUE</h3> <p>Thrown in case a function option does not provide an expected value
type for one of its returned object properties on execution.</p> <p><a id="ERR_INVALID_RETURN_VALUE"></a></p> <h3 id="err-invalid-return-value"><a href="#err-invalid-return-value" class="header-anchor">#</a> ERR_INVALID_RETURN_VALUE</h3> <p>Thrown in case a function option does not return an expected value
type on execution, such as when a function is expected to return a promise.</p> <p><a id="ERR_INVALID_SYNC_FORK_INPUT"></a></p> <h3 id="err-invalid-sync-fork-input"><a href="#err-invalid-sync-fork-input" class="header-anchor">#</a> ERR_INVALID_SYNC_FORK_INPUT</h3> <p>A <code>Buffer</code>, <code>TypedArray</code>, <code>DataView</code> or <code>string</code> was provided as stdio input to
an asynchronous fork. See the documentation for the <a href="/public/blog/node/child_process.html"><code>child_process</code></a> module
for more information.</p> <p><a id="ERR_INVALID_THIS"></a></p> <h3 id="err-invalid-this"><a href="#err-invalid-this" class="header-anchor">#</a> ERR_INVALID_THIS</h3> <p>A Node.js API function was called with an incompatible <code>this</code> value.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> urlSearchParams <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">URLSearchParams</span><span class="token punctuation">(</span><span class="token string">'foo=bar&amp;baz=new'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> buf <span class="token operator">=</span> Buffer<span class="token punctuation">.</span><span class="token function">alloc</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
urlSearchParams<span class="token punctuation">.</span><span class="token function">has</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span>buf<span class="token punctuation">,</span> <span class="token string">'foo'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// Throws a TypeError with code 'ERR_INVALID_THIS'</span>
</code></pre></div><p><a id="ERR_INVALID_TRANSFER_OBJECT"></a></p> <h3 id="err-invalid-transfer-object"><a href="#err-invalid-transfer-object" class="header-anchor">#</a> ERR_INVALID_TRANSFER_OBJECT</h3> <p>An invalid transfer object was passed to <code>postMessage()</code>.</p> <p><a id="ERR_INVALID_TUPLE"></a></p> <h3 id="err-invalid-tuple"><a href="#err-invalid-tuple" class="header-anchor">#</a> ERR_INVALID_TUPLE</h3> <p>An element in the <code>iterable</code> provided to the <a href="/public/blog/node/url.html#url_the_whatwg_url_api">WHATWG</a> <a href="/public/blog/node/url.html#url_constructor_new_urlsearchparams_iterable"><code>URLSearchParams</code> constructor</a> did not
represent a <code>[name, value]</code> tuple – that is, if an element is not iterable, or
does not consist of exactly two elements.</p> <p><a id="ERR_INVALID_URI"></a></p> <h3 id="err-invalid-uri"><a href="#err-invalid-uri" class="header-anchor">#</a> ERR_INVALID_URI</h3> <p>An invalid URI was passed.</p> <p><a id="ERR_INVALID_URL"></a></p> <h3 id="err-invalid-url"><a href="#err-invalid-url" class="header-anchor">#</a> ERR_INVALID_URL</h3> <p>An invalid URL was passed to the <a href="/public/blog/node/url.html#url_the_whatwg_url_api">WHATWG</a> <a href="/public/blog/node/url.html#url_constructor_new_url_input_base"><code>URL</code> constructor</a> to be parsed. The thrown error object
typically has an additional property <code>'input'</code> that contains the URL that failed
to parse.</p> <p><a id="ERR_INVALID_URL_SCHEME"></a></p> <h3 id="err-invalid-url-scheme"><a href="#err-invalid-url-scheme" class="header-anchor">#</a> ERR_INVALID_URL_SCHEME</h3> <p>An attempt was made to use a URL of an incompatible scheme (protocol) for a
specific purpose. It is only used in the <a href="/public/blog/node/url.html#url_the_whatwg_url_api">WHATWG URL API</a> support in the
<a href="/public/blog/node/fs.html"><code>fs</code></a> module (which only accepts URLs with <code>'file'</code> scheme), but may be used
in other Node.js APIs as well in the future.</p> <p><a id="ERR_IPC_CHANNEL_CLOSED"></a></p> <h3 id="err-ipc-channel-closed"><a href="#err-ipc-channel-closed" class="header-anchor">#</a> ERR_IPC_CHANNEL_CLOSED</h3> <p>An attempt was made to use an IPC communication channel that was already closed.</p> <p><a id="ERR_IPC_DISCONNECTED"></a></p> <h3 id="err-ipc-disconnected"><a href="#err-ipc-disconnected" class="header-anchor">#</a> ERR_IPC_DISCONNECTED</h3> <p>An attempt was made to disconnect an IPC communication channel that was already
disconnected. See the documentation for the <a href="/public/blog/node/child_process.html"><code>child_process</code></a> module
for more information.</p> <p><a id="ERR_IPC_ONE_PIPE"></a></p> <h3 id="err-ipc-one-pipe"><a href="#err-ipc-one-pipe" class="header-anchor">#</a> ERR_IPC_ONE_PIPE</h3> <p>An attempt was made to create a child Node.js process using more than one IPC
communication channel. See the documentation for the <a href="/public/blog/node/child_process.html"><code>child_process</code></a> module
for more information.</p> <p><a id="ERR_IPC_SYNC_FORK"></a></p> <h3 id="err-ipc-sync-fork"><a href="#err-ipc-sync-fork" class="header-anchor">#</a> ERR_IPC_SYNC_FORK</h3> <p>An attempt was made to open an IPC communication channel with a synchronously
forked Node.js process. See the documentation for the <a href="/public/blog/node/child_process.html"><code>child_process</code></a> module
for more information.</p> <p><a id="ERR_MANIFEST_ASSERT_INTEGRITY"></a></p> <h3 id="err-manifest-assert-integrity"><a href="#err-manifest-assert-integrity" class="header-anchor">#</a> ERR_MANIFEST_ASSERT_INTEGRITY</h3> <p>An attempt was made to load a resource, but the resource did not match the
integrity defined by the policy manifest. See the documentation for <a href="/public/blog/node/policy.html">policy</a>
manifests for more information.</p> <p><a id="ERR_MANIFEST_DEPENDENCY_MISSING"></a></p> <h3 id="err-manifest-dependency-missing"><a href="#err-manifest-dependency-missing" class="header-anchor">#</a> ERR_MANIFEST_DEPENDENCY_MISSING</h3> <p>An attempt was made to load a resource, but the resource was not listed as a
dependency from the location that attempted to load it. See the documentation
for <a href="/public/blog/node/policy.html">policy</a> manifests for more information.</p> <p><a id="ERR_MANIFEST_INTEGRITY_MISMATCH"></a></p> <h3 id="err-manifest-integrity-mismatch"><a href="#err-manifest-integrity-mismatch" class="header-anchor">#</a> ERR_MANIFEST_INTEGRITY_MISMATCH</h3> <p>An attempt was made to load a policy manifest, but the manifest had multiple
entries for a resource which did not match each other. Update the manifest
entries to match in order to resolve this error. See the documentation for
<a href="/public/blog/node/policy.html">policy</a> manifests for more information.</p> <p><a id="ERR_MANIFEST_INVALID_RESOURCE_FIELD"></a></p> <h3 id="err-manifest-invalid-resource-field"><a href="#err-manifest-invalid-resource-field" class="header-anchor">#</a> ERR_MANIFEST_INVALID_RESOURCE_FIELD</h3> <p>A policy manifest resource had an invalid value for one of its fields. Update
the manifest entry to match in order to resolve this error. See the
documentation for <a href="/public/blog/node/policy.html">policy</a> manifests for more information.</p> <p><a id="ERR_MANIFEST_PARSE_POLICY"></a></p> <h3 id="err-manifest-parse-policy"><a href="#err-manifest-parse-policy" class="header-anchor">#</a> ERR_MANIFEST_PARSE_POLICY</h3> <p>An attempt was made to load a policy manifest, but the manifest was unable to
be parsed. See the documentation for <a href="/public/blog/node/policy.html">policy</a> manifests for more information.</p> <p><a id="ERR_MANIFEST_TDZ"></a></p> <h3 id="err-manifest-tdz"><a href="#err-manifest-tdz" class="header-anchor">#</a> ERR_MANIFEST_TDZ</h3> <p>An attempt was made to read from a policy manifest, but the manifest
initialization has not yet taken place. This is likely a bug in Node.js.</p> <p><a id="ERR_MANIFEST_UNKNOWN_ONERROR"></a></p> <h3 id="err-manifest-unknown-onerror"><a href="#err-manifest-unknown-onerror" class="header-anchor">#</a> ERR_MANIFEST_UNKNOWN_ONERROR</h3> <p>A policy manifest was loaded, but had an unknown value for its &quot;onerror&quot;
behavior. See the documentation for <a href="/public/blog/node/policy.html">policy</a> manifests for more information.</p> <p><a id="ERR_MEMORY_ALLOCATION_FAILED"></a></p> <h3 id="err-memory-allocation-failed"><a href="#err-memory-allocation-failed" class="header-anchor">#</a> ERR_MEMORY_ALLOCATION_FAILED</h3> <p>An attempt was made to allocate memory (usually in the C++ layer) but it
failed.</p> <p><a id="ERR_METHOD_NOT_IMPLEMENTED"></a></p> <h3 id="err-method-not-implemented"><a href="#err-method-not-implemented" class="header-anchor">#</a> ERR_METHOD_NOT_IMPLEMENTED</h3> <p>A method is required but not implemented.</p> <p><a id="ERR_MISSING_ARGS"></a></p> <h3 id="err-missing-args"><a href="#err-missing-args" class="header-anchor">#</a> ERR_MISSING_ARGS</h3> <p>A required argument of a Node.js API was not passed. This is only used for
strict compliance with the API specification (which in some cases may accept
<code>func(undefined)</code> but not <code>func()</code>). In most native Node.js APIs,
<code>func(undefined)</code> and <code>func()</code> are treated identically, and the
<a href="#ERR_INVALID_ARG_TYPE"><code>ERR_INVALID_ARG_TYPE</code></a> error code may be used instead.</p> <p><a id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK"></a></p> <h3 id="err-missing-dynamic-instantiate-hook"><a href="#err-missing-dynamic-instantiate-hook" class="header-anchor">#</a> ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>An <a href="/public/blog/node/esm.html">ES Module</a> loader hook specified <code>format: 'dynamic'</code> but did not provide
a <code>dynamicInstantiate</code> hook.</p> <p><a id="ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST"></a></p> <h3 id="err-missing-message-port-in-transfer-list"><a href="#err-missing-message-port-in-transfer-list" class="header-anchor">#</a> ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST</h3> <p>A <code>MessagePort</code> was found in the object passed to a <code>postMessage()</code> call,
but not provided in the <code>transferList</code> for that call.</p> <p><a id="ERR_MISSING_PASSPHRASE"></a></p> <h3 id="err-missing-passphrase"><a href="#err-missing-passphrase" class="header-anchor">#</a> ERR_MISSING_PASSPHRASE</h3> <p>An attempt was made to read an encrypted key without specifying a passphrase.</p> <p><a id="ERR_MISSING_PLATFORM_FOR_WORKER"></a></p> <h3 id="err-missing-platform-for-worker"><a href="#err-missing-platform-for-worker" class="header-anchor">#</a> ERR_MISSING_PLATFORM_FOR_WORKER</h3> <p>The V8 platform used by this instance of Node.js does not support creating
Workers. This is caused by lack of embedder support for Workers. In particular,
this error will not occur with standard builds of Node.js.</p> <p><a id="ERR_MODULE_NOT_FOUND"></a></p> <h3 id="err-module-not-found"><a href="#err-module-not-found" class="header-anchor">#</a> ERR_MODULE_NOT_FOUND</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>An <a href="/public/blog/node/esm.html">ES Module</a> could not be resolved.</p> <p><a id="ERR_MULTIPLE_CALLBACK"></a></p> <h3 id="err-multiple-callback"><a href="#err-multiple-callback" class="header-anchor">#</a> ERR_MULTIPLE_CALLBACK</h3> <p>A callback was called more than once.</p> <p>A callback is almost always meant to only be called once as the query
can either be fulfilled or rejected but not both at the same time. The latter
would be possible by calling a callback more than once.</p> <p><a id="ERR_NAPI_CONS_FUNCTION"></a></p> <h3 id="err-napi-cons-function"><a href="#err-napi-cons-function" class="header-anchor">#</a> ERR_NAPI_CONS_FUNCTION</h3> <p>While using <code>N-API</code>, a constructor passed was not a function.</p> <p><a id="ERR_NAPI_INVALID_DATAVIEW_ARGS"></a></p> <h3 id="err-napi-invalid-dataview-args"><a href="#err-napi-invalid-dataview-args" class="header-anchor">#</a> ERR_NAPI_INVALID_DATAVIEW_ARGS</h3> <p>While calling <code>napi_create_dataview()</code>, a given <code>offset</code> was outside the bounds
of the dataview or <code>offset + length</code> was larger than a length of given <code>buffer</code>.</p> <p><a id="ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT"></a></p> <h3 id="err-napi-invalid-typedarray-alignment"><a href="#err-napi-invalid-typedarray-alignment" class="header-anchor">#</a> ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT</h3> <p>While calling <code>napi_create_typedarray()</code>, the provided <code>offset</code> was not a
multiple of the element size.</p> <p><a id="ERR_NAPI_INVALID_TYPEDARRAY_LENGTH"></a></p> <h3 id="err-napi-invalid-typedarray-length"><a href="#err-napi-invalid-typedarray-length" class="header-anchor">#</a> ERR_NAPI_INVALID_TYPEDARRAY_LENGTH</h3> <p>While calling <code>napi_create_typedarray()</code>, <code>(length * size_of_element) + byte_offset</code> was larger than the length of given <code>buffer</code>.</p> <p><a id="ERR_NAPI_TSFN_CALL_JS"></a></p> <h3 id="err-napi-tsfn-call-js"><a href="#err-napi-tsfn-call-js" class="header-anchor">#</a> ERR_NAPI_TSFN_CALL_JS</h3> <p>An error occurred while invoking the JavaScript portion of the thread-safe
function.</p> <p><a id="ERR_NAPI_TSFN_GET_UNDEFINED"></a></p> <h3 id="err-napi-tsfn-get-undefined"><a href="#err-napi-tsfn-get-undefined" class="header-anchor">#</a> ERR_NAPI_TSFN_GET_UNDEFINED</h3> <p>An error occurred while attempting to retrieve the JavaScript <code>undefined</code>
value.</p> <p><a id="ERR_NAPI_TSFN_START_IDLE_LOOP"></a></p> <h3 id="err-napi-tsfn-start-idle-loop"><a href="#err-napi-tsfn-start-idle-loop" class="header-anchor">#</a> ERR_NAPI_TSFN_START_IDLE_LOOP</h3> <p>On the main thread, values are removed from the queue associated with the
thread-safe function in an idle loop. This error indicates that an error
has occurred when attempting to start the loop.</p> <p><a id="ERR_NAPI_TSFN_STOP_IDLE_LOOP"></a></p> <h3 id="err-napi-tsfn-stop-idle-loop"><a href="#err-napi-tsfn-stop-idle-loop" class="header-anchor">#</a> ERR_NAPI_TSFN_STOP_IDLE_LOOP</h3> <p>Once no more items are left in the queue, the idle loop must be suspended. This
error indicates that the idle loop has failed to stop.</p> <p><a id="ERR_NO_CRYPTO"></a></p> <h3 id="err-no-crypto"><a href="#err-no-crypto" class="header-anchor">#</a> ERR_NO_CRYPTO</h3> <p>An attempt was made to use crypto features while Node.js was not compiled with
OpenSSL crypto support.</p> <p><a id="ERR_NO_ICU"></a></p> <h3 id="err-no-icu"><a href="#err-no-icu" class="header-anchor">#</a> ERR_NO_ICU</h3> <p>An attempt was made to use features that require <a href="/public/blog/node/intl.html#intl_internationalization_support">ICU</a>, but Node.js was not
compiled with ICU support.</p> <p><a id="ERR_NON_CONTEXT_AWARE_DISABLED"></a></p> <h3 id="err-non-context-aware-disabled"><a href="#err-non-context-aware-disabled" class="header-anchor">#</a> ERR_NON_CONTEXT_AWARE_DISABLED</h3> <p>A non-context-aware native addon was loaded in a process that disallows them.</p> <p><a id="ERR_OUT_OF_RANGE"></a></p> <h3 id="err-out-of-range"><a href="#err-out-of-range" class="header-anchor">#</a> ERR_OUT_OF_RANGE</h3> <p>A given value is out of the accepted range.</p> <p><a id="ERR_REQUIRE_ESM"></a></p> <h3 id="err-require-esm"><a href="#err-require-esm" class="header-anchor">#</a> ERR_REQUIRE_ESM</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>An attempt was made to <code>require()</code> an <a href="/public/blog/node/esm.html">ES Module</a>.</p> <p><a id="ERR_SCRIPT_EXECUTION_INTERRUPTED"></a></p> <h3 id="err-script-execution-interrupted"><a href="#err-script-execution-interrupted" class="header-anchor">#</a> ERR_SCRIPT_EXECUTION_INTERRUPTED</h3> <p>Script execution was interrupted by <code>SIGINT</code> (For example, when Ctrl+C was
pressed).</p> <p><a id="ERR_SCRIPT_EXECUTION_TIMEOUT"></a></p> <h3 id="err-script-execution-timeout"><a href="#err-script-execution-timeout" class="header-anchor">#</a> ERR_SCRIPT_EXECUTION_TIMEOUT</h3> <p>Script execution timed out, possibly due to bugs in the script being executed.</p> <p><a id="ERR_SERVER_ALREADY_LISTEN"></a></p> <h3 id="err-server-already-listen"><a href="#err-server-already-listen" class="header-anchor">#</a> ERR_SERVER_ALREADY_LISTEN</h3> <p>The <a href="/public/blog/node/net.html#net_server_listen"><code>server.listen()</code></a> method was called while a <code>net.Server</code> was already
listening. This applies to all instances of <code>net.Server</code>, including HTTP, HTTPS,
and HTTP/2 <code>Server</code> instances.</p> <p><a id="ERR_SERVER_NOT_RUNNING"></a></p> <h3 id="err-server-not-running"><a href="#err-server-not-running" class="header-anchor">#</a> ERR_SERVER_NOT_RUNNING</h3> <p>The <a href="/public/blog/node/net.html#net_server_close_callback"><code>server.close()</code></a> method was called when a <code>net.Server</code> was not
running. This applies to all instances of <code>net.Server</code>, including HTTP, HTTPS,
and HTTP/2 <code>Server</code> instances.</p> <p><a id="ERR_SOCKET_ALREADY_BOUND"></a></p> <h3 id="err-socket-already-bound"><a href="#err-socket-already-bound" class="header-anchor">#</a> ERR_SOCKET_ALREADY_BOUND</h3> <p>An attempt was made to bind a socket that has already been bound.</p> <p><a id="ERR_SOCKET_BAD_BUFFER_SIZE"></a></p> <h3 id="err-socket-bad-buffer-size"><a href="#err-socket-bad-buffer-size" class="header-anchor">#</a> ERR_SOCKET_BAD_BUFFER_SIZE</h3> <p>An invalid (negative) size was passed for either the <code>recvBufferSize</code> or
<code>sendBufferSize</code> options in <a href="/public/blog/node/dgram.html#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>.</p> <p><a id="ERR_SOCKET_BAD_PORT"></a></p> <h3 id="err-socket-bad-port"><a href="#err-socket-bad-port" class="header-anchor">#</a> ERR_SOCKET_BAD_PORT</h3> <p>An API function expecting a port &gt;= 0 and &lt; 65536 received an invalid value.</p> <p><a id="ERR_SOCKET_BAD_TYPE"></a></p> <h3 id="err-socket-bad-type"><a href="#err-socket-bad-type" class="header-anchor">#</a> ERR_SOCKET_BAD_TYPE</h3> <p>An API function expecting a socket type (<code>udp4</code> or <code>udp6</code>) received an invalid
value.</p> <p><a id="ERR_SOCKET_BUFFER_SIZE"></a></p> <h3 id="err-socket-buffer-size"><a href="#err-socket-buffer-size" class="header-anchor">#</a> ERR_SOCKET_BUFFER_SIZE</h3> <p>While using <a href="/public/blog/node/dgram.html#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>, the size of the receive or send <code>Buffer</code>
could not be determined.</p> <p><a id="ERR_SOCKET_CANNOT_SEND"></a></p> <h3 id="err-socket-cannot-send"><a href="#err-socket-cannot-send" class="header-anchor">#</a> ERR_SOCKET_CANNOT_SEND</h3> <p>Data could be sent on a socket.</p> <p><a id="ERR_SOCKET_CLOSED"></a></p> <h3 id="err-socket-closed"><a href="#err-socket-closed" class="header-anchor">#</a> ERR_SOCKET_CLOSED</h3> <p>An attempt was made to operate on an already closed socket.</p> <p><a id="ERR_SOCKET_DGRAM_IS_CONNECTED"></a></p> <h3 id="err-socket-dgram-is-connected"><a href="#err-socket-dgram-is-connected" class="header-anchor">#</a> ERR_SOCKET_DGRAM_IS_CONNECTED</h3> <p>A <a href="/public/blog/node/dgram.html#dgram_socket_connect_port_address_callback"><code>dgram.connect()</code></a> call was made on an already connected socket.</p> <p><a id="ERR_SOCKET_DGRAM_NOT_CONNECTED"></a></p> <h3 id="err-socket-dgram-not-connected"><a href="#err-socket-dgram-not-connected" class="header-anchor">#</a> ERR_SOCKET_DGRAM_NOT_CONNECTED</h3> <p>A <a href="/public/blog/node/dgram.html#dgram_socket_disconnect"><code>dgram.disconnect()</code></a> or <a href="/public/blog/node/dgram.html#dgram_socket_remoteaddress"><code>dgram.remoteAddress()</code></a> call was made on a
disconnected socket.</p> <p><a id="ERR_SOCKET_DGRAM_NOT_RUNNING"></a></p> <h3 id="err-socket-dgram-not-running"><a href="#err-socket-dgram-not-running" class="header-anchor">#</a> ERR_SOCKET_DGRAM_NOT_RUNNING</h3> <p>A call was made and the UDP subsystem was not running.</p> <p><a id="ERR_SRI_PARSE"></a></p> <h3 id="err-sri-parse"><a href="#err-sri-parse" class="header-anchor">#</a> ERR_SRI_PARSE</h3> <p>A string was provided for a Subresource Integrity check, but was unable to be
parsed. Check the format of integrity attributes by looking at the
<a href="https://www.w3.org/TR/SRI/#the-integrity-attribute" target="_blank" rel="noopener noreferrer">Subresource Integrity specification<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" x="0px" y="0px" viewBox="0 0 100 100" width="15" height="15" class="icon outbound"><path fill="currentColor" d="M18.8,85.1h56l0,0c2.2,0,4-1.8,4-4v-32h-8v28h-48v-48h28v-8h-32l0,0c-2.2,0-4,1.8-4,4v56C14.8,83.3,16.6,85.1,18.8,85.1z"></path> <polygon fill="currentColor" points="45.7,48.7 51.3,54.3 77.2,28.5 77.2,37.2 85.2,37.2 85.2,14.9 62.8,14.9 62.8,22.9 71.5,22.9"></polygon></svg></a>.</p> <p><a id="ERR_STREAM_CANNOT_PIPE"></a></p> <h3 id="err-stream-cannot-pipe"><a href="#err-stream-cannot-pipe" class="header-anchor">#</a> ERR_STREAM_CANNOT_PIPE</h3> <p>An attempt was made to call <a href="/public/blog/node/stream.html#stream_readable_pipe_destination_options"><code>stream.pipe()</code></a> on a <a href="/public/blog/node/stream.html#stream_class_stream_writable"><code>Writable</code></a> stream.</p> <p><a id="ERR_STREAM_DESTROYED"></a></p> <h3 id="err-stream-destroyed"><a href="#err-stream-destroyed" class="header-anchor">#</a> ERR_STREAM_DESTROYED</h3> <p>A stream method was called that cannot complete because the stream was
destroyed using <code>stream.destroy()</code>.</p> <p><a id="ERR_STREAM_ALREADY_FINISHED"></a></p> <h3 id="err-stream-already-finished"><a href="#err-stream-already-finished" class="header-anchor">#</a> ERR_STREAM_ALREADY_FINISHED</h3> <p>A stream method was called that cannot complete because the stream was
finished.</p> <p><a id="ERR_STREAM_NULL_VALUES"></a></p> <h3 id="err-stream-null-values"><a href="#err-stream-null-values" class="header-anchor">#</a> ERR_STREAM_NULL_VALUES</h3> <p>An attempt was made to call <a href="/public/blog/node/stream.html#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> with a <code>null</code> chunk.</p> <p><a id="ERR_STREAM_PREMATURE_CLOSE"></a></p> <h3 id="err-stream-premature-close"><a href="#err-stream-premature-close" class="header-anchor">#</a> ERR_STREAM_PREMATURE_CLOSE</h3> <p>An error returned by <code>stream.finished()</code> and <code>stream.pipeline()</code>, when a stream
or a pipeline ends non gracefully with no explicit error.</p> <p><a id="ERR_STREAM_PUSH_AFTER_EOF"></a></p> <h3 id="err-stream-push-after-eof"><a href="#err-stream-push-after-eof" class="header-anchor">#</a> ERR_STREAM_PUSH_AFTER_EOF</h3> <p>An attempt was made to call <a href="/public/blog/node/stream.html#stream_readable_push_chunk_encoding"><code>stream.push()</code></a> after a <code>null</code>(EOF) had been
pushed to the stream.</p> <p><a id="ERR_STREAM_UNSHIFT_AFTER_END_EVENT"></a></p> <h3 id="err-stream-unshift-after-end-event"><a href="#err-stream-unshift-after-end-event" class="header-anchor">#</a> ERR_STREAM_UNSHIFT_AFTER_END_EVENT</h3> <p>An attempt was made to call <a href="/public/blog/node/stream.html#stream_readable_unshift_chunk_encoding"><code>stream.unshift()</code></a> after the <code>'end'</code> event was
emitted.</p> <p><a id="ERR_STREAM_WRAP"></a></p> <h3 id="err-stream-wrap"><a href="#err-stream-wrap" class="header-anchor">#</a> ERR_STREAM_WRAP</h3> <p>Prevents an abort if a string decoder was set on the Socket or if the decoder
is in <code>objectMode</code>.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> Socket <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'net'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>Socket<span class="token punctuation">;</span>
<span class="token keyword">const</span> instance <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Socket</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

instance<span class="token punctuation">.</span><span class="token function">setEncoding</span><span class="token punctuation">(</span><span class="token string">'utf8'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p><a id="ERR_STREAM_WRITE_AFTER_END"></a></p> <h3 id="err-stream-write-after-end"><a href="#err-stream-write-after-end" class="header-anchor">#</a> ERR_STREAM_WRITE_AFTER_END</h3> <p>An attempt was made to call <a href="/public/blog/node/stream.html#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> after <code>stream.end()</code> has been
called.</p> <p><a id="ERR_STRING_TOO_LONG"></a></p> <h3 id="err-string-too-long"><a href="#err-string-too-long" class="header-anchor">#</a> ERR_STRING_TOO_LONG</h3> <p>An attempt has been made to create a string longer than the maximum allowed
length.</p> <p><a id="ERR_SYNTHETIC"></a></p> <h3 id="err-synthetic"><a href="#err-synthetic" class="header-anchor">#</a> ERR_SYNTHETIC</h3> <p>An artificial error object used to capture the call stack for diagnostic
reports.</p> <p><a id="ERR_SYSTEM_ERROR"></a></p> <h3 id="err-system-error"><a href="#err-system-error" class="header-anchor">#</a> ERR_SYSTEM_ERROR</h3> <p>An unspecified or non-specific system error has occurred within the Node.js
process. The error object will have an <code>err.info</code> object property with
additional details.</p> <p><a id="ERR_TLS_CERT_ALTNAME_INVALID"></a></p> <h3 id="err-tls-cert-altname-invalid"><a href="#err-tls-cert-altname-invalid" class="header-anchor">#</a> ERR_TLS_CERT_ALTNAME_INVALID</h3> <p>While using TLS, the hostname/IP of the peer did not match any of the
<code>subjectAltNames</code> in its certificate.</p> <p><a id="ERR_TLS_DH_PARAM_SIZE"></a></p> <h3 id="err-tls-dh-param-size"><a href="#err-tls-dh-param-size" class="header-anchor">#</a> ERR_TLS_DH_PARAM_SIZE</h3> <p>While using TLS, the parameter offered for the Diffie-Hellman (<code>DH</code>)
key-agreement protocol is too small. By default, the key length must be greater
than or equal to 1024 bits to avoid vulnerabilities, even though it is strongly
recommended to use 2048 bits or larger for stronger security.</p> <p><a id="ERR_TLS_HANDSHAKE_TIMEOUT"></a></p> <h3 id="err-tls-handshake-timeout"><a href="#err-tls-handshake-timeout" class="header-anchor">#</a> ERR_TLS_HANDSHAKE_TIMEOUT</h3> <p>A TLS/SSL handshake timed out. In this case, the server must also abort the
connection.</p> <p><a id="ERR_TLS_INVALID_PROTOCOL_METHOD"></a></p> <h3 id="err-tls-invalid-protocol-method"><a href="#err-tls-invalid-protocol-method" class="header-anchor">#</a> ERR_TLS_INVALID_PROTOCOL_METHOD</h3> <p>The specified  <code>secureProtocol</code> method is invalid. It is  either unknown, or
disabled because it is insecure.</p> <p><a id="ERR_TLS_INVALID_PROTOCOL_VERSION"></a></p> <h3 id="err-tls-invalid-protocol-version"><a href="#err-tls-invalid-protocol-version" class="header-anchor">#</a> ERR_TLS_INVALID_PROTOCOL_VERSION</h3> <p>Valid TLS protocol versions are <code>'TLSv1'</code>, <code>'TLSv1.1'</code>, or <code>'TLSv1.2'</code>.</p> <p><a id="ERR_TLS_PROTOCOL_VERSION_CONFLICT"></a></p> <h3 id="err-tls-protocol-version-conflict"><a href="#err-tls-protocol-version-conflict" class="header-anchor">#</a> ERR_TLS_PROTOCOL_VERSION_CONFLICT</h3> <p>Attempting to set a TLS protocol <code>minVersion</code> or <code>maxVersion</code> conflicts with an
attempt to set the <code>secureProtocol</code> explicitly. Use one mechanism or the other.</p> <p><a id="ERR_TLS_RENEGOTIATION_DISABLED"></a></p> <h3 id="err-tls-renegotiation-disabled"><a href="#err-tls-renegotiation-disabled" class="header-anchor">#</a> ERR_TLS_RENEGOTIATION_DISABLED</h3> <p>An attempt was made to renegotiate TLS on a socket instance with TLS disabled.</p> <p><a id="ERR_TLS_REQUIRED_SERVER_NAME"></a></p> <h3 id="err-tls-required-server-name"><a href="#err-tls-required-server-name" class="header-anchor">#</a> ERR_TLS_REQUIRED_SERVER_NAME</h3> <p>While using TLS, the <code>server.addContext()</code> method was called without providing
a hostname in the first parameter.</p> <p><a id="ERR_TLS_SESSION_ATTACK"></a></p> <h3 id="err-tls-session-attack"><a href="#err-tls-session-attack" class="header-anchor">#</a> ERR_TLS_SESSION_ATTACK</h3> <p>An excessive amount of TLS renegotiations is detected, which is a potential
vector for denial-of-service attacks.</p> <p><a id="ERR_TLS_SNI_FROM_SERVER"></a></p> <h3 id="err-tls-sni-from-server"><a href="#err-tls-sni-from-server" class="header-anchor">#</a> ERR_TLS_SNI_FROM_SERVER</h3> <p>An attempt was made to issue Server Name Indication from a TLS server-side
socket, which is only valid from a client.</p> <p><a id="ERR_TRACE_EVENTS_CATEGORY_REQUIRED"></a></p> <h3 id="err-trace-events-category-required"><a href="#err-trace-events-category-required" class="header-anchor">#</a> ERR_TRACE_EVENTS_CATEGORY_REQUIRED</h3> <p>The <code>trace_events.createTracing()</code> method requires at least one trace event
category.</p> <p><a id="ERR_TRACE_EVENTS_UNAVAILABLE"></a></p> <h3 id="err-trace-events-unavailable"><a href="#err-trace-events-unavailable" class="header-anchor">#</a> ERR_TRACE_EVENTS_UNAVAILABLE</h3> <p>The <code>trace_events</code> module could not be loaded because Node.js was compiled with
the <code>--without-v8-platform</code> flag.</p> <p><a id="ERR_TRANSFERRING_EXTERNALIZED_SHAREDARRAYBUFFER"></a></p> <h3 id="err-transferring-externalized-sharedarraybuffer"><a href="#err-transferring-externalized-sharedarraybuffer" class="header-anchor">#</a> ERR_TRANSFERRING_EXTERNALIZED_SHAREDARRAYBUFFER</h3> <p>A <code>SharedArrayBuffer</code> whose memory is not managed by the JavaScript engine
or by Node.js was encountered during serialization. Such a <code>SharedArrayBuffer</code>
cannot be serialized.</p> <p>This can only happen when native addons create <code>SharedArrayBuffer</code>s in
&quot;externalized&quot; mode, or put existing <code>SharedArrayBuffer</code> into externalized mode.</p> <p><a id="ERR_TRANSFORM_ALREADY_TRANSFORMING"></a></p> <h3 id="err-transform-already-transforming"><a href="#err-transform-already-transforming" class="header-anchor">#</a> ERR_TRANSFORM_ALREADY_TRANSFORMING</h3> <p>A <code>Transform</code> stream finished while it was still transforming.</p> <p><a id="ERR_TRANSFORM_WITH_LENGTH_0"></a></p> <h3 id="err-transform-with-length-0"><a href="#err-transform-with-length-0" class="header-anchor">#</a> ERR_TRANSFORM_WITH_LENGTH_0</h3> <p>A <code>Transform</code> stream finished with data still in the write buffer.</p> <p><a id="ERR_TTY_INIT_FAILED"></a></p> <h3 id="err-tty-init-failed"><a href="#err-tty-init-failed" class="header-anchor">#</a> ERR_TTY_INIT_FAILED</h3> <p>The initialization of a TTY failed due to a system error.</p> <p><a id="ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET"></a></p> <h3 id="err-uncaught-exception-capture-already-set"><a href="#err-uncaught-exception-capture-already-set" class="header-anchor">#</a> ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET</h3> <p><a href="/public/blog/node/process.html#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> was called twice,
without first resetting the callback to <code>null</code>.</p> <p>This error is designed to prevent accidentally overwriting a callback registered
from another module.</p> <p><a id="ERR_UNESCAPED_CHARACTERS"></a></p> <h3 id="err-unescaped-characters"><a href="#err-unescaped-characters" class="header-anchor">#</a> ERR_UNESCAPED_CHARACTERS</h3> <p>A string that contained unescaped characters was received.</p> <p><a id="ERR_UNHANDLED_ERROR"></a></p> <h3 id="err-unhandled-error"><a href="#err-unhandled-error" class="header-anchor">#</a> ERR_UNHANDLED_ERROR</h3> <p>An unhandled error occurred (for instance, when an <code>'error'</code> event is emitted
by an <a href="/public/blog/node/events.html#events_class_eventemitter"><code>EventEmitter</code></a> but an <code>'error'</code> handler is not registered).</p> <p><a id="ERR_UNKNOWN_BUILTIN_MODULE"></a></p> <h3 id="err-unknown-builtin-module"><a href="#err-unknown-builtin-module" class="header-anchor">#</a> ERR_UNKNOWN_BUILTIN_MODULE</h3> <p>Used to identify a specific kind of internal Node.js error that should not
typically be triggered by user code. Instances of this error point to an
internal bug within the Node.js binary itself.</p> <p><a id="ERR_UNKNOWN_CREDENTIAL"></a></p> <h3 id="err-unknown-credential"><a href="#err-unknown-credential" class="header-anchor">#</a> ERR_UNKNOWN_CREDENTIAL</h3> <p>A Unix group or user identifier that does not exist was passed.</p> <p><a id="ERR_UNKNOWN_ENCODING"></a></p> <h3 id="err-unknown-encoding"><a href="#err-unknown-encoding" class="header-anchor">#</a> ERR_UNKNOWN_ENCODING</h3> <p>An invalid or unknown encoding option was passed to an API.</p> <p><a id="ERR_UNKNOWN_FILE_EXTENSION"></a></p> <h3 id="err-unknown-file-extension"><a href="#err-unknown-file-extension" class="header-anchor">#</a> ERR_UNKNOWN_FILE_EXTENSION</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>An attempt was made to load a module with an unknown or unsupported file
extension.</p> <p><a id="ERR_UNKNOWN_MODULE_FORMAT"></a></p> <h3 id="err-unknown-module-format"><a href="#err-unknown-module-format" class="header-anchor">#</a> ERR_UNKNOWN_MODULE_FORMAT</h3> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>An attempt was made to load a module with an unknown or unsupported format.</p> <p><a id="ERR_UNKNOWN_SIGNAL"></a></p> <h3 id="err-unknown-signal"><a href="#err-unknown-signal" class="header-anchor">#</a> ERR_UNKNOWN_SIGNAL</h3> <p>An invalid or unknown process signal was passed to an API expecting a valid
signal (such as <a href="/public/blog/node/child_process.html#child_process_subprocess_kill_signal"><code>subprocess.kill()</code></a>).</p> <p><a id="ERR_V8BREAKITERATOR"></a></p> <h3 id="err-v8breakiterator"><a href="#err-v8breakiterator" class="header-anchor">#</a> ERR_V8BREAKITERATOR</h3> <p>The V8 <code>BreakIterator</code> API was used but the full ICU data set is not installed.</p> <p><a id="ERR_VALID_PERFORMANCE_ENTRY_TYPE"></a></p> <h3 id="err-valid-performance-entry-type"><a href="#err-valid-performance-entry-type" class="header-anchor">#</a> ERR_VALID_PERFORMANCE_ENTRY_TYPE</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), no valid performance
entry types were found.</p> <p><a id="ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING"></a></p> <h3 id="err-vm-dynamic-import-callback-missing"><a href="#err-vm-dynamic-import-callback-missing" class="header-anchor">#</a> ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING</h3> <p>A dynamic import callback was not specified.</p> <p><a id="ERR_VM_MODULE_ALREADY_LINKED"></a></p> <h3 id="err-vm-module-already-linked"><a href="#err-vm-module-already-linked" class="header-anchor">#</a> ERR_VM_MODULE_ALREADY_LINKED</h3> <p>The module attempted to be linked is not eligible for linking, because of one of
the following reasons:</p> <ul><li>It has already been linked (<code>linkingStatus</code> is <code>'linked'</code>)</li> <li>It is being linked (<code>linkingStatus</code> is <code>'linking'</code>)</li> <li>Linking has failed for this module (<code>linkingStatus</code> is <code>'errored'</code>)</li></ul> <p><a id="ERR_VM_MODULE_DIFFERENT_CONTEXT"></a></p> <h3 id="err-vm-module-different-context"><a href="#err-vm-module-different-context" class="header-anchor">#</a> ERR_VM_MODULE_DIFFERENT_CONTEXT</h3> <p>The module being returned from the linker function is from a different context
than the parent module. Linked modules must share the same context.</p> <p><a id="ERR_VM_MODULE_LINKING_ERRORED"></a></p> <h3 id="err-vm-module-linking-errored"><a href="#err-vm-module-linking-errored" class="header-anchor">#</a> ERR_VM_MODULE_LINKING_ERRORED</h3> <p>The linker function returned a module for which linking has failed.</p> <p><a id="ERR_VM_MODULE_NOT_MODULE"></a></p> <h3 id="err-vm-module-not-module"><a href="#err-vm-module-not-module" class="header-anchor">#</a> ERR_VM_MODULE_NOT_MODULE</h3> <p>The fulfilled value of a linking promise is not a <code>vm.Module</code> object.</p> <p><a id="ERR_VM_MODULE_STATUS"></a></p> <h3 id="err-vm-module-status"><a href="#err-vm-module-status" class="header-anchor">#</a> ERR_VM_MODULE_STATUS</h3> <p>The current module's status does not allow for this operation. The specific
meaning of the error depends on the specific function.</p> <p><a id="ERR_WORKER_INVALID_EXEC_ARGV"></a></p> <h3 id="err-worker-invalid-exec-argv"><a href="#err-worker-invalid-exec-argv" class="header-anchor">#</a> ERR_WORKER_INVALID_EXEC_ARGV</h3> <p>The <code>execArgv</code> option passed to the <code>Worker</code> constructor contains
invalid flags.</p> <p><a id="ERR_WORKER_OUT_OF_MEMORY"></a></p> <h3 id="err-worker-out-of-memory"><a href="#err-worker-out-of-memory" class="header-anchor">#</a> ERR_WORKER_OUT_OF_MEMORY</h3> <p>The <code>Worker</code> instance terminated because it reached its memory limit.</p> <p><a id="ERR_WORKER_PATH"></a></p> <h3 id="err-worker-path"><a href="#err-worker-path" class="header-anchor">#</a> ERR_WORKER_PATH</h3> <p>The path for the main script of a worker is neither an absolute path
nor a relative path starting with <code>./</code> or <code>../</code>.</p> <p><a id="ERR_WORKER_UNSERIALIZABLE_ERROR"></a></p> <h3 id="err-worker-unserializable-error"><a href="#err-worker-unserializable-error" class="header-anchor">#</a> ERR_WORKER_UNSERIALIZABLE_ERROR</h3> <p>All attempts at serializing an uncaught exception from a worker thread failed.</p> <p><a id="ERR_WORKER_UNSUPPORTED_EXTENSION"></a></p> <h3 id="err-worker-unsupported-extension"><a href="#err-worker-unsupported-extension" class="header-anchor">#</a> ERR_WORKER_UNSUPPORTED_EXTENSION</h3> <p>The pathname used for the main script of a worker has an
unknown file extension.</p> <p><a id="ERR_WORKER_UNSUPPORTED_OPERATION"></a></p> <h3 id="err-worker-unsupported-operation"><a href="#err-worker-unsupported-operation" class="header-anchor">#</a> ERR_WORKER_UNSUPPORTED_OPERATION</h3> <p>The requested functionality is not supported in worker threads.</p> <p><a id="ERR_ZLIB_INITIALIZATION_FAILED"></a></p> <h3 id="err-zlib-initialization-failed"><a href="#err-zlib-initialization-failed" class="header-anchor">#</a> ERR_ZLIB_INITIALIZATION_FAILED</h3> <p>Creation of a <a href="/public/blog/node/zlib.html"><code>zlib</code></a> object failed due to incorrect configuration.</p> <p><a id="HPE_HEADER_OVERFLOW"></a></p> <h3 id="hpe-header-overflow"><a href="#hpe-header-overflow" class="header-anchor">#</a> HPE_HEADER_OVERFLOW</h3> <p>Too much HTTP header data was received. In order to protect against malicious or
malconfigured clients, if more than 8KB of HTTP header data is received then
HTTP parsing will abort without a request or response object being created, and
an <code>Error</code> with this code will be emitted.</p> <p><a id="MODULE_NOT_FOUND"></a></p> <h3 id="module-not-found"><a href="#module-not-found" class="header-anchor">#</a> MODULE_NOT_FOUND</h3> <p>A module file could not be resolved while attempting a <a href="/public/blog/node/modules.html#modules_require_id"><code>require()</code></a> or
<code>import</code> operation.</p> <h2 id="legacy-node-js-error-codes"><a href="#legacy-node-js-error-codes" class="header-anchor">#</a> Legacy Node.js Error Codes</h2> <blockquote><p>Stability: 0 - Deprecated. These error codes are either inconsistent, or have
been removed.</p></blockquote> <p><a id="ERR_CANNOT_TRANSFER_OBJECT"></a></p> <h3 id="err-cannot-transfer-object"><a href="#err-cannot-transfer-object" class="header-anchor">#</a> ERR_CANNOT_TRANSFER_OBJECT</h3> <p>The value passed to <code>postMessage()</code> contained an object that is not supported
for transferring.</p> <p><a id="ERR_CLOSED_MESSAGE_PORT"></a></p> <h3 id="err-closed-message-port"><a href="#err-closed-message-port" class="header-anchor">#</a> ERR_CLOSED_MESSAGE_PORT</h3> <p>There was an attempt to use a <code>MessagePort</code> instance in a closed
state, usually after <code>.close()</code> has been called.</p> <p><a id="ERR_CRYPTO_HASH_DIGEST_NO_UTF16"></a></p> <h3 id="err-crypto-hash-digest-no-utf16"><a href="#err-crypto-hash-digest-no-utf16" class="header-anchor">#</a> ERR_CRYPTO_HASH_DIGEST_NO_UTF16</h3> <p>The UTF-16 encoding was used with <a href="/public/blog/node/crypto.html#crypto_hash_digest_encoding"><code>hash.digest()</code></a>. While the
<code>hash.digest()</code> method does allow an <code>encoding</code> argument to be passed in,
causing the method to return a string rather than a <code>Buffer</code>, the UTF-16
encoding (e.g. <code>ucs</code> or <code>utf16le</code>) is not supported.</p> <p><a id="ERR_HTTP2_FRAME_ERROR"></a></p> <h3 id="err-http2-frame-error"><a href="#err-http2-frame-error" class="header-anchor">#</a> ERR_HTTP2_FRAME_ERROR</h3> <p>Used when a failure occurs sending an individual frame on the HTTP/2
session.</p> <p><a id="ERR_HTTP2_HEADERS_OBJECT"></a></p> <h3 id="err-http2-headers-object"><a href="#err-http2-headers-object" class="header-anchor">#</a> ERR_HTTP2_HEADERS_OBJECT</h3> <p>Used when an HTTP/2 Headers Object is expected.</p> <p><a id="ERR_HTTP2_HEADER_REQUIRED"></a></p> <h3 id="err-http2-header-required"><a href="#err-http2-header-required" class="header-anchor">#</a> ERR_HTTP2_HEADER_REQUIRED</h3> <p>Used when a required header is missing in an HTTP/2 message.</p> <p><a id="ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND"></a></p> <h3 id="err-http2-info-headers-after-respond"><a href="#err-http2-info-headers-after-respond" class="header-anchor">#</a> ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND</h3> <p>HTTP/2 informational headers must only be sent <em>prior</em> to calling the
<code>Http2Stream.prototype.respond()</code> method.</p> <p><a id="ERR_HTTP2_STREAM_CLOSED"></a></p> <h3 id="err-http2-stream-closed"><a href="#err-http2-stream-closed" class="header-anchor">#</a> ERR_HTTP2_STREAM_CLOSED</h3> <p>Used when an action has been performed on an HTTP/2 Stream that has already
been closed.</p> <p><a id="ERR_HTTP_INVALID_CHAR"></a></p> <h3 id="err-http-invalid-char"><a href="#err-http-invalid-char" class="header-anchor">#</a> ERR_HTTP_INVALID_CHAR</h3> <p>Used when an invalid character is found in an HTTP response status message
(reason phrase).</p> <p><a id="ERR_INDEX_OUT_OF_RANGE"></a></p> <h3 id="err-index-out-of-range"><a href="#err-index-out-of-range" class="header-anchor">#</a> ERR_INDEX_OUT_OF_RANGE</h3> <p>A given index was out of the accepted range (e.g. negative offsets).</p> <p><a id="ERR_NAPI_CONS_PROTOTYPE_OBJECT"></a></p> <h3 id="err-napi-cons-prototype-object"><a href="#err-napi-cons-prototype-object" class="header-anchor">#</a> ERR_NAPI_CONS_PROTOTYPE_OBJECT</h3> <p>Used by the <code>N-API</code> when <code>Constructor.prototype</code> is not an object.</p> <p><a id="ERR_NO_LONGER_SUPPORTED"></a></p> <h3 id="err-no-longer-supported"><a href="#err-no-longer-supported" class="header-anchor">#</a> ERR_NO_LONGER_SUPPORTED</h3> <p>A Node.js API was called in an unsupported manner, such as
<code>Buffer.write(string, encoding, offset[, length])</code>.</p> <p><a id="ERR_OUTOFMEMORY"></a></p> <h3 id="err-outofmemory"><a href="#err-outofmemory" class="header-anchor">#</a> ERR_OUTOFMEMORY</h3> <p>Used generically to identify that an operation caused an out of memory
condition.</p> <p><a id="ERR_PARSE_HISTORY_DATA"></a></p> <h3 id="err-parse-history-data"><a href="#err-parse-history-data" class="header-anchor">#</a> ERR_PARSE_HISTORY_DATA</h3> <p>The <code>repl</code> module was unable to parse data from the REPL history file.</p> <p><a id="ERR_STDERR_CLOSE"></a></p> <h3 id="err-stderr-close"><a href="#err-stderr-close" class="header-anchor">#</a> ERR_STDERR_CLOSE</h3> <p>An attempt was made to close the <code>process.stderr</code> stream. By design, Node.js
does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p> <p><a id="ERR_STDOUT_CLOSE"></a></p> <h3 id="err-stdout-close"><a href="#err-stdout-close" class="header-anchor">#</a> ERR_STDOUT_CLOSE</h3> <p>An attempt was made to close the <code>process.stdout</code> stream. By design, Node.js
does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p> <p><a id="ERR_STREAM_READ_NOT_IMPLEMENTED"></a></p> <h3 id="err-stream-read-not-implemented"><a href="#err-stream-read-not-implemented" class="header-anchor">#</a> ERR_STREAM_READ_NOT_IMPLEMENTED</h3> <p>Used when an attempt is made to use a readable stream that has not implemented
<a href="/public/blog/node/stream.html#stream_readable_read_size_1"><code>readable._read()</code></a>.</p> <p><a id="ERR_TLS_RENEGOTIATION_FAILED"></a></p> <h3 id="err-tls-renegotiation-failed"><a href="#err-tls-renegotiation-failed" class="header-anchor">#</a> ERR_TLS_RENEGOTIATION_FAILED</h3> <p>Used when a TLS renegotiation request has failed in a non-specific way.</p> <p><a id="ERR_UNKNOWN_BUILTIN_MODULE"></a></p> <h3 id="err-unknown-builtin-module-2"><a href="#err-unknown-builtin-module-2" class="header-anchor">#</a> ERR_UNKNOWN_BUILTIN_MODULE</h3> <p>The <code>'ERR_UNKNOWN_BUILTIN_MODULE'</code> error code is used to identify a specific
kind of internal Node.js error that should not typically be triggered by user
code. Instances of this error point to an internal bug within the Node.js
binary itself.</p> <p><a id="ERR_UNKNOWN_STDIN_TYPE"></a></p> <h3 id="err-unknown-stdin-type"><a href="#err-unknown-stdin-type" class="header-anchor">#</a> ERR_UNKNOWN_STDIN_TYPE</h3> <p>An attempt was made to launch a Node.js process with an unknown <code>stdin</code> file
type. This error is usually an indication of a bug within Node.js itself,
although it is possible for user code to trigger it.</p> <p><a id="ERR_UNKNOWN_STREAM_TYPE"></a></p> <h3 id="err-unknown-stream-type"><a href="#err-unknown-stream-type" class="header-anchor">#</a> ERR_UNKNOWN_STREAM_TYPE</h3> <p>An attempt was made to launch a Node.js process with an unknown <code>stdout</code> or
<code>stderr</code> file type. This error is usually an indication of a bug within Node.js
itself, although it is possible for user code to trigger it.</p> <p><a id="ERR_VALUE_OUT_OF_RANGE"></a></p> <h3 id="err-value-out-of-range"><a href="#err-value-out-of-range" class="header-anchor">#</a> ERR_VALUE_OUT_OF_RANGE</h3> <p>Used when a given value is out of the accepted range.</p> <p><a id="ERR_VM_MODULE_NOT_LINKED"></a></p> <h3 id="err-vm-module-not-linked"><a href="#err-vm-module-not-linked" class="header-anchor">#</a> ERR_VM_MODULE_NOT_LINKED</h3> <p>The module must be successfully linked before instantiation.</p> <p><a id="ERR_ZLIB_BINDING_CLOSED"></a></p> <h3 id="err-zlib-binding-closed"><a href="#err-zlib-binding-closed" class="header-anchor">#</a> ERR_ZLIB_BINDING_CLOSED</h3> <p>Used when an attempt is made to use a <code>zlib</code> object after it has already been
closed.</p> <h3 id="other-error-codes"><a href="#other-error-codes" class="header-anchor">#</a> Other error codes</h3> <p>These errors have never been released, but had been present on master between
releases.</p> <p><a id="ERR_ENTRY_TYPE_MISMATCH"></a></p> <h4 id="err-entry-type-mismatch"><a href="#err-entry-type-mismatch" class="header-anchor">#</a> ERR_ENTRY_TYPE_MISMATCH</h4> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>The <code>--entry-type=commonjs</code> flag was used to attempt to execute an <code>.mjs</code> file
or a <code>.js</code> file where the nearest parent <code>package.json</code> contains
<code>&quot;type&quot;: &quot;module&quot;</code>; or
the <code>--entry-type=module</code> flag was used to attempt to execute a <code>.cjs</code> file or
a <code>.js</code> file where the nearest parent <code>package.json</code> either lacks a <code>&quot;type&quot;</code>
field or contains <code>&quot;type&quot;: &quot;commonjs&quot;</code>.</p> <p><a id="ERR_FS_WATCHER_ALREADY_STARTED"></a></p> <h4 id="err-fs-watcher-already-started"><a href="#err-fs-watcher-already-started" class="header-anchor">#</a> ERR_FS_WATCHER_ALREADY_STARTED</h4> <p>An attempt was made to start a watcher returned by <code>fs.watch()</code> that has
already been started.</p> <p><a id="ERR_FS_WATCHER_NOT_STARTED"></a></p> <h4 id="err-fs-watcher-not-started"><a href="#err-fs-watcher-not-started" class="header-anchor">#</a> ERR_FS_WATCHER_NOT_STARTED</h4> <p>An attempt was made to initiate operations on a watcher returned by
<code>fs.watch()</code> that has not yet been started.</p> <p><a id="ERR_HTTP2_ALREADY_SHUTDOWN"></a></p> <h4 id="err-http2-already-shutdown"><a href="#err-http2-already-shutdown" class="header-anchor">#</a> ERR_HTTP2_ALREADY_SHUTDOWN</h4> <p>Occurs with multiple attempts to shutdown an HTTP/2 session.</p> <p><a id="ERR_HTTP2_ERROR"></a></p> <h4 id="err-http2-error-2"><a href="#err-http2-error-2" class="header-anchor">#</a> ERR_HTTP2_ERROR</h4> <p>A non-specific HTTP/2 error has occurred.</p> <p><a id="ERR_INVALID_REPL_HISTORY"></a></p> <h4 id="err-invalid-repl-history"><a href="#err-invalid-repl-history" class="header-anchor">#</a> ERR_INVALID_REPL_HISTORY</h4> <p>Used in the <code>repl</code> in case the old history file is used and an error occurred
while trying to read and parse it.</p> <p><a id="ERR_INVALID_REPL_TYPE"></a></p> <h4 id="err-invalid-repl-type"><a href="#err-invalid-repl-type" class="header-anchor">#</a> ERR_INVALID_REPL_TYPE</h4> <blockquote><p>Stability: 1 - Experimental</p></blockquote> <p>The <code>--entry-type=...</code> flag is not compatible with the Node.js REPL.</p> <p><a id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK"></a></p> <h4 id="err-missing-dynamic-instantiate-hook-2"><a href="#err-missing-dynamic-instantiate-hook-2" class="header-anchor">#</a> ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</h4> <p>Used when an <a href="/public/blog/node/esm.html">ES Module</a> loader hook specifies <code>format: 'dynamic'</code> but does
not provide a <code>dynamicInstantiate</code> hook.</p> <p><a id="ERR_STREAM_HAS_STRINGDECODER"></a></p> <h4 id="err-stream-has-stringdecoder"><a href="#err-stream-has-stringdecoder" class="header-anchor">#</a> ERR_STREAM_HAS_STRINGDECODER</h4> <p>Used to prevent an abort if a string decoder was set on the Socket.</p> <div class="language-js extra-class"><pre class="language-js"><code><span class="token keyword">const</span> Socket <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'net'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>Socket<span class="token punctuation">;</span>
<span class="token keyword">const</span> instance <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Socket</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

instance<span class="token punctuation">.</span><span class="token function">setEncoding</span><span class="token punctuation">(</span><span class="token string">'utf8'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><p><a id="ERR_STRING_TOO_LARGE"></a></p> <h4 id="err-string-too-large"><a href="#err-string-too-large" class="header-anchor">#</a> ERR_STRING_TOO_LARGE</h4> <p>An attempt has been made to create a string larger than the maximum allowed
size.</p> <p><a id="ERR_TTY_WRITABLE_NOT_READABLE"></a></p> <h4 id="err-tty-writable-not-readable"><a href="#err-tty-writable-not-readable" class="header-anchor">#</a> ERR_TTY_WRITABLE_NOT_READABLE</h4> <p>This <code>Error</code> is thrown when a read is attempted on a TTY <code>WriteStream</code>,
such as <code>process.stdout.on('data')</code>.</p></div> <footer class="page-edit"><!----> <!----></footer> <!----> </main></div><div class="global-ui"><!----></div></div>
    <script src="/public/blog/assets/js/app.793d18d6.js" defer></script><script src="/public/blog/assets/js/2.d1dd4e4d.js" defer></script><script src="/public/blog/assets/js/25.151f485c.js" defer></script><script src="/public/blog/assets/js/3.1f730cd9.js" defer></script>
  </body>
</html>
